import type { City } from "./types";

export const cities: City[] = [
  {
    id: "athens",
    aliases: ["athens"],
    coords: [23.73, 37.98],
    tier: 1,
    names: [
      { from: -800, to: 1456, zh: "雅典", lat: "Athenae", native: "Αθηναι" },
      { from: 1456, to: 1830, zh: "雅典（奥斯曼治下）", native: "Atina" },
    ],
    active: { from: -800, to: 9999 },
    polities: [
      { from: -800, to: -338, polity: "雅典城邦" },
      { from: -337, to: 1452, polity: "希腊化/罗马-拜占庭世界" },
      { from: 1453, to: 1829, polity: "奥斯曼帝国" },
      { from: 1830, to: 9999, polity: "希腊" },
    ],
    description: "古希腊核心城邦，民主制与海上同盟的象征。",
  },
  {
    id: "sparta",
    aliases: ["sparta"],
    coords: [22.43, 37.08],
    tier: 1,
    names: [{ from: -900, to: 9999, zh: "斯巴达", lat: "Sparta", native: "Σπαρτη" }],
    active: { from: -900, to: 9999 },
    polities: [{ from: -900, to: -146, polity: "拉科尼亚/斯巴达" }],
    description: "伯罗奔尼撒半岛的军事城邦，与雅典共同定义古典希腊时代。",
  },
  {
    id: "rome",
    aliases: ["rome", "roma"],
    coords: [12.49, 41.89],
    tier: 1,
    names: [{ from: -753, to: 9999, zh: "罗马", lat: "Roma" }],
    active: { from: -753, to: 9999 },
    polities: [
      { from: -753, to: -509, polity: "罗马王政" },
      { from: -508, to: -27, polity: "罗马共和国" },
      { from: -26, to: 476, polity: "罗马帝国" },
      { from: 477, to: 1869, polity: "教皇国/意大利诸邦" },
      { from: 1870, to: 9999, polity: "意大利" },
    ],
    description: "从城邦、共和国到帝国的欧洲政治母题之一。",
  },
  {
    id: "constantinople",
    aliases: ["constantinople", "istanbul", "byzantium"],
    coords: [28.98, 41.01],
    tier: 1,
    names: [
      { from: -660, to: 329, zh: "拜占庭", lat: "Byzantium" },
      { from: 330, to: 1453, zh: "君士坦丁堡", lat: "Constantinopolis" },
      { from: 1453, to: 9999, zh: "伊斯坦布尔", native: "Istanbul" },
    ],
    active: { from: -660, to: 9999 },
    polities: [
      { from: 330, to: 1452, polity: "东罗马帝国" },
      { from: 1453, to: 1922, polity: "奥斯曼帝国" },
      { from: 1923, to: 9999, polity: "土耳其" },
    ],
    description: "连接黑海与地中海的帝国都城，1453 年是欧洲史的关键节点。",
  },
  {
    id: "alexandria",
    aliases: ["alexandria"],
    coords: [29.92, 31.2],
    tier: 1,
    names: [{ from: -331, to: 9999, zh: "亚历山大里亚", lat: "Alexandria" }],
    active: { from: -331, to: 9999 },
    polities: [
      { from: -331, to: -30, polity: "托勒密埃及" },
      { from: -29, to: 640, polity: "罗马/拜占庭埃及" },
      { from: 641, to: 1516, polity: "伊斯兰王朝埃及" },
      { from: 1517, to: 1913, polity: "奥斯曼埃及" },
    ],
    description: "希腊化世界的知识与贸易中心，地中海南岸的门户。",
  },
  {
    id: "babylon",
    aliases: ["babylon"],
    coords: [44.42, 32.54],
    tier: 1,
    names: [{ from: -1900, to: 200, zh: "巴比伦", lat: "Babylon" }],
    active: { from: -1900, to: 200 },
    polities: [{ from: -1900, to: -539, polity: "巴比伦诸王朝" }],
    description: "两河流域的古老都市，近东世界的早期坐标。",
  },
  {
    id: "paris",
    aliases: ["paris", "lutetia"],
    coords: [2.35, 48.86],
    tier: 1,
    names: [
      { from: -250, to: 300, zh: "卢泰西亚", lat: "Lutetia" },
      { from: 301, to: 9999, zh: "巴黎", lat: "Paris" },
    ],
    active: { from: -250, to: 9999 },
    polities: [{ from: 987, to: 1789, polity: "法兰西王国" }],
    description: "从高卢城市成长为法兰西政治与文化中心。",
  },
  {
    id: "london",
    aliases: ["london", "londinium"],
    coords: [-0.13, 51.51],
    tier: 1,
    names: [
      { from: 43, to: 410, zh: "伦蒂尼恩", lat: "Londinium" },
      { from: 411, to: 9999, zh: "伦敦", lat: "London" },
    ],
    active: { from: 43, to: 9999 },
    polities: [{ from: 1066, to: 1706, polity: "英格兰王国" }],
    description: "罗马不列颠的城镇，后来成为英格兰与大英帝国的核心。",
  },
  {
    id: "carthage",
    aliases: ["carthage", "carthago"],
    coords: [10.33, 36.85],
    tier: 1,
    names: [{ from: -814, to: 698, zh: "迦太基", lat: "Carthago", native: "Qart Hadasht" }],
    active: { from: -814, to: 698 },
    polities: [
      { from: -814, to: -146, polity: "迦太基" },
      { from: -145, to: 439, polity: "罗马阿非利加" },
    ],
    description: "腓尼基人在北非建立的海上强权，罗马共和国的主要对手。",
  },
  {
    id: "jerusalem",
    aliases: ["jerusalem", "hierosolyma"],
    coords: [35.21, 31.77],
    tier: 1,
    names: [{ from: -1800, to: 9999, zh: "耶路撒冷", lat: "Hierosolyma" }],
    active: { from: -1800, to: 9999 },
    polities: [{ from: -1000, to: -586, polity: "以色列/犹大王国" }],
    description: "犹太教、基督教与伊斯兰教共同牵连的圣城。",
  },
  {
    id: "miletus",
    aliases: ["miletus"],
    coords: [27.28, 37.53],
    tier: 2,
    names: [{ from: -1000, to: 1400, zh: "米利都", lat: "Miletus" }],
    active: { from: -1000, to: 1400 },
    polities: [{ from: -800, to: -494, polity: "爱奥尼亚城邦" }],
    description: "爱奥尼亚海岸的重要城邦，自然哲学传统的发源地之一。",
  },
  {
    id: "venice",
    aliases: ["venice", "venetia"],
    coords: [12.32, 45.44],
    tier: 2,
    names: [{ from: 421, to: 9999, zh: "威尼斯", lat: "Venetia" }],
    active: { from: 421, to: 9999 },
    polities: [{ from: 697, to: 1797, polity: "威尼斯共和国" }],
    description: "亚得里亚海商贸共和国，中世纪与近代早期地中海贸易枢纽。",
  },
];
