/** Administrative reading groups only; no provincial polygons or annual control claims. */
export const notitiaDateNote='《官职志》保存了四世纪末至五世纪不同时间的记录，并非 395 年同一天的完整名册。下列分组用于理解治理层次；行省举例不能直接当作当年边界。';
const latin=(page:string)=>`https://www.intratext.com/IXT/LAT0212/${page}.HTM`;
export interface AdministrativeReadingGroup {
 id:string;division:'gaul'|'italy'|'illyricum'|'east';name:string;modern:string;
 provinces:string[];note:string;regions:[string,string][];cities:[string,string][];source:string;
}
export const administrativeReadingGroups:AdministrativeReadingGroup[]=[
 {id:'britains',division:'gaul',name:'不列颠管区',modern:'海峡以北，今英格兰与威尔士为主的罗马统治区。',
  provinces:['第一不列颠','第二不列颠','弗拉维亚·凯撒里恩西斯','马克西马·凯撒里恩西斯','瓦伦提亚'],
  note:'名册中的省名仍需与考古、地理研究配合定位，尤其瓦伦提亚位置存在讨论。不据这五个名称把苏格兰和爱尔兰全岛划入罗马。',
  regions:[['britain','罗马不列颠']],cities:[['london','伦底尼乌姆'],['york','埃博拉库姆（约克）']],source:latin('_P3')},
 {id:'spains',division:'gaul',name:'西班牙管区',modern:'伊比利亚半岛、巴利阿里群岛，以及直布罗陀海峡南岸的廷吉塔纳。',
  provinces:['贝提卡','卢西塔尼亚','加莱西亚','塔拉科南西斯','卡塔吉南西斯','巴利阿里群岛','毛里塔尼亚·廷吉塔纳'],
  note:'“西班牙”是古代行政名称，范围跨越今天西班牙、葡萄牙与摩洛哥北部。廷吉塔纳与更东面的凯撒里恩西斯、锡提芬西斯分别阅读。',
  regions:[['hispania','伊比利亚半岛'],['mauretania','毛里塔尼亚沿岸对照']],cities:[['tarraco','塔拉科'],['emerita','埃梅里塔']],source:latin('_P3')},
 {id:'gauls',division:'gaul',name:'高卢诸省与南部七省',modern:'今法国大部，并延伸至莱茵河边区、比利时与阿尔卑斯西侧。',
  provinces:['第一、第二贝尔吉卡','第一、第二日耳曼尼亚','卢格杜南西斯诸省','第一、第二阿基坦','第一、第二纳尔波南西斯','维恩南西斯','九族省'],
  note:'此卡合并南北高卢作阅读导览。《官职志》在“七省”标题下列了更多省名，不能将该标题解释成整个高卢刚好只有七省，也不能把贝尔吉卡直接等同现代比利时。',
  regions:[['gaul','高卢总览']],cities:[['trier','特里尔'],['lyon','卢格杜努姆（里昂）'],['arles','阿雷拉特（阿尔勒）']],source:latin('_P3')},
 {id:'italian-provinces',division:'italy',name:'意大利诸省：北部、罗马周边与岛屿',modern:'意大利半岛、阿尔卑斯南北部分地域，以及西西里、撒丁和科西嘉。',
  provinces:['威尼提亚与伊斯特里亚','艾米利亚','利古里亚','图斯基亚与翁布里亚','坎帕尼亚','西西里','第一、第二雷提亚'],
  note:'北部意大利与罗马周边有不同的行政代理体系；罗马城市长官也不等于管辖整个意大利。此卡把它们合并定位，没有把北部、南部和各岛画成一个行省。',
  regions:[['italy','意大利半岛'],['islands','西地中海岛屿'],['alps','阿尔卑斯边区']],cities:[['milan','米兰'],['rome','罗马'],['syracuse','叙拉古']],source:latin('_P2')},
 {id:'western-illyricum',division:'italy',name:'西部伊利里库姆：潘诺尼亚及邻近诸省',modern:'多瑙河中游、东阿尔卑斯与亚得里亚海东岸方向。',
  provinces:['第一、第二潘诺尼亚','萨维亚','达尔马提亚','内陆诺里库姆','河岸诺里库姆'],
  note:'名册西部也出现“伊利里库姆”，它与东部的同名行政大区不是同一范围。现代研究指出巴尔干分组的记录年代并不一致；这里不据晚期名单裁定 395 年各边缘的实际管辖。',
  regions:[['pannonia','潘诺尼亚与达尔马提亚'],['alps','阿尔卑斯地域对照']],cities:[['sirmium','西尔米乌姆'],['salona','萨洛纳']],source:latin('_P2')},
 {id:'african-provinces',division:'italy',name:'阿非利加管区与迦太基周边',modern:'今阿尔及利亚、突尼斯和利比亚西部的部分北非沿岸。',
  provinces:['拜扎凯纳','努米底亚','毛里塔尼亚·锡提芬西斯','毛里塔尼亚·凯撒里恩西斯','的黎波里塔纳'],
  note:'迦太基所在的阿非利加总督省具有特殊总督体系，不能仅凭管区名单的省数处理其全部关系。海峡南岸的廷吉塔纳列在西班牙组，昔兰尼加则随埃及组阅读。',
  regions:[['africa','迦太基与阿非利加'],['byzacena','拜扎凯纳：苏塞与杰姆'],['numidia5','努米底亚：希波与内陆城市'],['mauretania','毛里塔尼亚地域对照'],['libya','的黎波里与昔兰尼加对照']],cities:[['carthage','迦太基'],['hadrumetum','哈德鲁梅图姆（苏塞）'],['thysdrus','提斯德鲁斯（杰姆）'],['hippo','希波（安纳巴）'],['cirta','基尔塔（君士坦丁）'],['cuicul','奎库尔（杰米拉）'],['timgad','提姆加德'],['lepcis','大莱普提斯']],source:latin('_P2')},
 {id:'macedonian-provinces',division:'illyricum',name:'马其顿管区',modern:'巴尔干南部、希腊大陆与克里特方向。',
  provinces:['阿该亚','马其顿','色萨利','旧伊庇鲁斯','新伊庇鲁斯','克里特'],
  note:'马其顿管区比同名行省更大，也不等同今天北马其顿国家。《官职志》还记有部分“萨卢塔里斯马其顿”；巴尔干名单需结合其分期阅读。',
  regions:[['greece','希腊大陆与马其顿'],['crete','克里特']],cities:[['thessaloniki','塞萨洛尼基'],['athens','雅典'],['gortyn','戈尔廷']],source:latin('_P19')},
 {id:'dacian-provinces',division:'illyricum',name:'达契亚管区：多瑙河南岸',modern:'今塞尔维亚、保加利亚及邻近巴尔干内陆的部分地域。',
  provinces:['内陆达契亚','河岸达契亚','第一默西亚','达尔达尼亚','普雷瓦利塔纳'],
  note:'河以南继续使用“达契亚”名称，与早已放弃的河北旧行省区别开。名册还把部分“萨卢塔里斯马其顿”列在此组；这些记录不能被拼成精确的 395 年省界。',
  regions:[['thrace','巴尔干与多瑙河南岸对照']],cities:[['serdica','塞尔迪卡（索非亚）']],source:latin('_P19')},
 {id:'thracian-provinces',division:'east',name:'色雷斯管区',modern:'巴尔干东部，连接多瑙河下游、黑海西岸和马尔马拉海。',
  provinces:['欧罗巴','色雷斯','海米蒙图斯','罗多彼','第二默西亚','斯基泰'],
  note:'欧罗巴在这里是一个行省名，不是整个欧洲；斯基泰指黑海西岸的罗马行省，也不是整个欧亚草原。君士坦丁堡另有首都城市长官体系。',
  regions:[['thrace','色雷斯与巴尔干东部']],cities:[['byzantium','君士坦丁堡'],['hadrianople','阿德里安堡']],source:latin('_P18')},
 {id:'asian-provinces',division:'east',name:'亚细亚管区',modern:'小亚细亚西部与西南部，面向爱琴海，涉及部分岛屿。',
  provinces:['吕底亚','卡里亚','吕基亚','潘菲利亚','皮西迪亚','帕卡提亚纳与萨卢塔里斯弗里吉亚','群岛省'],
  note:'管区、亚细亚总督省和整个亚洲大陆是三个不同尺度。《官职志》另列亚细亚总督，不应把管区所列举的名称当作整个小亚细亚的全部行省。',
  regions:[['asia','小亚细亚西部']],cities:[['ephesus','以弗所']],source:latin('_P18')},
 {id:'pontic-provinces',division:'east',name:'本都管区',modern:'小亚细亚北部与内陆，从比提尼亚、黑海沿岸到卡帕多基亚方向。',
  provinces:['比提尼亚','加拉太','第一、第二卡帕多基亚','赫勒诺本都','波勒蒙本都','第一、第二亚美尼亚'],
  note:'比提尼亚的尼科米底亚在这一行政组中。第一、第二亚美尼亚是罗马行省名称，不等于把整个亚美尼亚高原及王国全部纳入罗马。',
  regions:[['pontus','本都与卡帕多基亚']],cities:[['nicomedia','尼科米底亚'],['caesarea-cappadocia','卡帕多基亚凯撒利亚']],source:latin('_P18')},
 {id:'oriental-provinces',division:'east',name:'东方管区：东地中海与两河边区',modern:'小亚细亚东南部、叙利亚—巴勒斯坦沿岸、约旦与上两河边区，另含塞浦路斯。',
  provinces:['叙利亚','腓尼基','巴勒斯坦诸省','阿拉伯','奇里乞亚','奥斯罗恩','美索不达米亚','塞浦路斯'],
  note:'东方管区是东方行政大区的一部分。美索不达米亚省不能等同整个两河流域；尼西比斯在 363 年割让后，不能因名册列有这个省名就改回罗马归属。',
  regions:[['levant','叙利亚与巴勒斯坦'],['arabia','阿拉伯行省'],['mesopotamia','两河边区'],['cyprus','塞浦路斯']],cities:[['antioch','安条克'],['edessa','埃德萨'],['bosra','布斯拉']],source:latin('_P18')},
 {id:'egyptian-provinces',division:'east',name:'埃及管区与昔兰尼加',modern:'尼罗河三角洲、河谷，以及今利比亚东部地中海沿岸。',
  provinces:['埃及','阿卡迪亚','底比斯','上利比亚','下利比亚'],
  note:'这是东方大区内的一组行政地域；上、下利比亚是晚期省名，不等同现代利比亚全境。“上埃及／下埃及”的河流地理导览也不等于逐个行省划分。',
  regions:[['egypt','埃及总览'],['egypt-delta','下埃及三角洲'],['egypt-upper','上埃及河谷'],['libya','昔兰尼加与西部对照']],cities:[['alexandria','亚历山大里亚'],['syene','叙恩（阿斯旺）'],['cyrene','昔兰尼']],source:latin('_P18')},
];
export const administrativeGroupsAt=(division:string,year:number)=>year===395?administrativeReadingGroups.filter(g=>g.division===division):[];
