import type {GazetteerPlace} from './model';
import type {HistoricalDetail,HistoricalFact} from './history-details';
import {courseSources} from './course-sources';

type Source=keyof typeof courseSources;
const fact=(text:string,...sources:Source[]):HistoricalFact=>({text,sources});
const site=(id:string,name:string,modern:string,aliases:string[],coords:[number,number],source:Source,description:string):GazetteerPlace=>({id,name,modern,aliases,coords,source:courseSources[source].url,description,kind:'历史地点参考'});
export const classicalCoursePlaces:GazetteerPlace[]=[
 site('sardis','萨迪斯','土耳其 · 萨尔特附近',['Sardis','Sardes','Sart','萨第斯','萨尔迪斯','吕底亚','Lydia'],[28+2/60+43/3600,38+28/60+55/3600],'sardisCoords','吕底亚故都，后来成为波斯行省中心；位于爱琴海与安纳托利亚内陆之间。坐标取遗址代表点。'),
 site('babylon','巴比伦','伊拉克 · 希拉附近',['Babylon','Babil','Bābili','巴比伦尼亚'],[44.42497815,32.53729695],'babylonCoords','幼发拉底河地区的重要古城，帮助理解波斯与亚历山大统治的东方腹地。代表点不是帝国疆界。'),
 site('pergamon','帕加马','土耳其 · 贝尔加马',['Pergamon','Pergamum','Bergama','帕加蒙','佩加蒙','别迦摩','阿塔罗斯','阿塔罗王朝'],[27.18,39+7/60+33/3600],'pergamonCoords','安纳托利亚西部的希腊化王国中心，课程译作帕加马。坐标取世界遗产古城分项代表点。'),
];
const unknownPeople=fact('本条没有可靠的全城居民比例。王朝、军队与当地人口分别理解，不把统治者的身份直接覆盖到所有居民。');
const unknownLanguage=fact('尚未收录这一时段的本地语言分布资料，不从政治归属推定每位居民的母语。');
const scale=fact('这里标出城市或遗址位置；城市辖区、王国领土和军队经过的区域分开理解。本批未新增经核实的疆界多边形。');
const sardis={placeId:'sardis',title:'萨迪斯',kind:'历史城市' as const,displayName:'Sardis / Sardes',territory:fact('位于赫尔摩斯平原边缘、特摩洛斯山麓，是爱琴海通向内陆的节点。城堡与行省范围不同。','sardisHistory'),people:unknownPeople,language:fact('古名可见吕底亚语、波斯语与希腊语形式；这些名称证据不能换算成同一年的居民语言比例。','sardisHistory'),nameNote:fact('吕底亚语 Sfar-、波斯语 Sparda 和希腊语 Sardis 是同一地点的名称线索，今地名 Sart 仍保留痕迹。','sardisHistory'),related:['miletus','babylon','pergamon']};
const babylon={placeId:'babylon',title:'巴比伦',displayName:'Babylon / Bābili',kind:'历史城市' as const,territory:scale,people:unknownPeople,language:fact('巴比伦的地名有阿卡德语 Bābili 等记载；名称资料不是居民母语普查。','babylonCoords'),nameNote:fact('巴比伦城位于今天伊拉克希拉附近。巴比伦尼亚是更广的历史区域，不能与城市标记等同。','babylonCoords'),related:['sardis','alexandria']};
const pergamon={placeId:'pergamon',title:'帕加马',displayName:'Pergamon / Pergamum',kind:'王国中心' as const,territory:fact('山丘上的卫城俯瞰巴克尔恰伊平原。城墙围合的城市和阿塔罗斯王国的领地是两个尺度。','pergamon'),people:unknownPeople,language:unknownLanguage,nameNote:fact('课程中的帕加马，又译帕加蒙、佩加蒙，对应今天土耳其贝尔加马的古城。','pergamon'),related:['rome','sardis','alexandria']};
const alexandria={placeId:'alexandria',title:'亚历山大里亚',displayName:'Alexandria',kind:'历史城市' as const,territory:scale,people:unknownPeople,language:unknownLanguage,nameNote:fact('这里是埃及尼罗河三角洲西侧的亚历山大城；亚历山大建立的其他同名城市不在此点。'),related:['babylon','pergamon','rome']};
const carthage={placeId:'carthage',title:'迦太基',displayName:'Carthago / Carthage',kind:'历史城市' as const,territory:fact('突尼斯湾的本城与伊比利亚的新迦太基分开定位。汉尼拔的行军线表示军事行动，不代表沿途全部永久并入迦太基。'),people:fact('这里是布匿文明的重要中心；贸易、军事活动涉及不同地区的人群，不能把全体军人或全城居民视作单一人口类别。','carthageSite'),language:unknownLanguage,nameNote:fact('北非迦太基位于今天突尼斯附近；新迦太基则在今天西班牙卡塔赫纳。'),related:['rome','new-carthage','syracuse']};

const antioch={placeId:'antioch',title:'安条克',displayName:'Antiocheia / Antiochia',kind:'王国中心' as const,territory:fact('奥龙特斯河流域的政治中心。古代叙利亚是历史区域，不与现代叙利亚国界完全重合；这处遗址今天位于土耳其。','antiochHistory'),people:fact('城市的希腊化制度与移民背景，不代表周边居民都具有同一种身份。本条没有全城居民构成比例。'),language:unknownLanguage,nameNote:fact('这里指奥龙特斯河畔的安条克，现代安塔基亚；古代其他名为安条克的城市不合并到这个点。','antiochHistory'),related:['alexandria','pergamon','babylon'],reading:[{chapter:51,pages:[393,394],note:'课程讨论塞琉古与托勒密；城市具体分期由外部历史资料补充。'}] as HistoricalDetail['reading']};

export const classicalCourseDetails:HistoricalDetail[]=[
 {...antioch,id:'antioch-antiochus-iii',from:-223,to:-188,focusYear:-218,period:'安条克三世时代：前 223—188 年选段',polity:fact('塞琉古王国的重要政治中心。安条克三世向东恢复势力，也与埃及托勒密王国争夺南方地区；两国的战争说明希腊化世界存在多个国家。','seleucid'),readingNote:'本段止于与罗马议和的前 188 年，不把这一窗口视为塞琉古王国的全部存续期；疆域在战争前后变化显著。'},
 {...antioch,id:'antioch-roman-takeover',from:-64,to:-64,focusYear:-64,period:'前 64 年罗马接管之后',kind:'历史城市',polity:fact('按庞培到来并终结塞琉古残余王权之后记录，安条克进入罗马的叙利亚行省体系。','seleucid'),people:unknownPeople,readingNote:'从安条克三世到罗马接管之间，尚有内战、王朝争夺及亚美尼亚控制等阶段未录入；地图不将空白期自动延长为同一统治。'},
 {...carthage,id:'carthage-post-zama',from:-201,to:-150,focusYear:-180,period:'扎马战败后的迦太基：前 201—150 年',polity:fact('战后迦太基保留自己的法律和城市自治，城内不驻罗马军队，但军事行动受到罗马严格限制，并承担赔款。战败并不等于当时已经成为罗马行省。','zamaTreaty'),territory:fact('和约保留部分非洲领地，并要求归还马西尼萨及其祖先的领地；有关具体范围的争端不能用一句“归还”转成精确边界。','zamaTreaty'),reading:[{chapter:69,pages:[580,582]}],readingNote:'课程把扎马战役与和约连写；本条从前 201 年的战后秩序开始。其军力和外交受限，与罗马直接吞并是不同关系。',relatedBattles:['hannibal']},
 {...sardis,id:'sardis-lydian',from:-600,to:-550,focusYear:-560,period:'吕底亚都城：前 600—550 年选段',polity:fact('吕底亚王国的都城。这是波斯征服之前的选段，前 550 年是本条资料截止点，不是吕底亚灭亡年份。','sardisHistory'),reading:[{chapter:20,pages:[153,156]}]},
 {...sardis,id:'sardis-persian',from:-540,to:-335,focusYear:-500,period:'波斯行省中心：前 540—335 年选段',polity:fact('阿契美尼德波斯帝国在小亚细亚的重要行省中心，也是对希腊军事行动的集结地点。','sardisHistory'),reading:[{chapter:20,pages:[156,156]},{chapter:44,pages:[339,340]}],readingNote:'本段从已属波斯统治的前 540 年开始，不以它作为征服吕底亚的精确年份；波斯影响希腊城邦，也不等于直接统治所有希腊城市。'},
 {...sardis,id:'sardis-alexander',from:-334,to:-324,focusYear:-330,period:'亚历山大取得城市后：前 334—324 年',polity:fact('按前 334 年征服之后记录，萨迪斯进入亚历山大的统治空间。本段止于其去世前，继承者争夺不自动沿用这一归属。','sardisHistory','alexander'),reading:[{chapter:46,pages:[359,360]}]},
 {...babylon,id:'babylon-persian',from:-539,to:-332,focusYear:-500,period:'波斯统治：前 539—332 年',polity:fact('按居鲁士前 539 年取得巴比伦之后记录，城市纳入阿契美尼德波斯帝国；巴比伦城延续，原王朝的独立统治终结。','persia'),reading:[{chapter:20,pages:[156,156]}]},
 {...babylon,id:'babylon-alexander',from:-331,to:-324,focusYear:-330,period:'亚历山大取得城市后：前 331—324 年',polity:fact('按亚历山大进入巴比伦之后记录，这里处于其统治之下；随后东征继续，不能把巴比伦作为全部征服行动的终点。'),reading:[{chapter:46,pages:[360,360]}],readingNote:'前 323 年亚历山大在巴比伦去世，随后进入继承与分裂问题。本条止于前 324 年，避免用一个全年标签掩盖转折。',readingNoteSource:'alexander'},
 {...pergamon,id:'pergamon-attalid',from:-250,to:-134,focusYear:-218,period:'阿塔罗斯王朝中心：前 250—134 年选段',polity:fact('希腊化世界中的阿塔罗斯王朝中心。它与埃及托勒密王国属于不同政治实体，“希腊化”不是统一国家名称。','pergamon'),reading:[{chapter:73,pages:[613,613]}]},
 {...pergamon,id:'pergamon-bequest',from:-133,to:-133,period:'前 133 年王国遗赠',polity:fact('末代国王将王国遗赠罗马。这是罗马取得继承主张的节点，不把遗赠文本直接等同于全境当天完成行政接管。','pergamon'),reading:[{chapter:73,pages:[613,613]}],readingNote:'课程讲到王国遗赠。本条只标记这一节点；后续争夺、行省设置和具体辖区仍待补充。'},
 {...alexandria,id:'alexandria-early',from:-330,to:-324,focusYear:-330,period:'亚历山大时期的新城：前 330—324 年选段',polity:fact('处于亚历山大统治的埃及，新城开始发展。不能将它在托勒密时期成熟的都城角色提前到刚建城时。'),reading:[{chapter:46,pages:[359,360]}],readingNote:'课程把建城与取代孟菲斯连写；地图将早期新城和后来托勒密都城分别呈现。'},
 {...alexandria,id:'alexandria-ptolemy',from:-305,to:-31,focusYear:-218,period:'托勒密王国：前 305—31 年',kind:'王国中心',polity:fact('托勒密王朝在埃及的政治中心，属于亚历山大征服之后形成的希腊化王国。前 31 年阿克提翁败战尚不等于埃及已被罗马正式接管。','ptolemaic'),people:fact('马其顿—希腊统治集团与埃及本地社会应分别观察。埃及宗教和艺术传统延续，也出现与希腊文化的互动。','ptolemaic'),language:fact('课程提到希腊语与埃及语之间的行政翻译。这里记录多语言背景，不把课程的精英人口比例当作亚历山大城人口统计。'),reading:[{chapter:51,pages:[393,394]}],readingNote:'“希腊化”不意味着本地文化消失；课程关于分隔的解释与博物馆介绍的文化交流，应结合具体时期和证据阅读。',readingNoteSource:'ptolemaic',relatedBattles:['actium']},
 {...alexandria,id:'alexandria-roman',from:-30,to:-30,period:'前 30 年罗马取得埃及后',polity:fact('按罗马接管埃及之后记录，托勒密王朝统治终结。前 31 年的阿克提翁海战与前 30 年的政权易手分开定位。','ptolemaic'),reading:[{chapter:51,pages:[394,394],note:'希腊化时期终点的关联阅读，政治分期另据博物馆资料。'}],relatedBattles:['actium']},
 {...carthage,id:'carthage-hannibal',from:-218,to:-202,focusYear:-218,period:'第二次布匿战争：前 218—202 年',polity:fact('迦太基与罗马共和国交战。汉尼拔从伊比利亚向意大利进军，北非本城仍是迦太基的政治中心。'),reading:[{chapter:69,pages:[579,581]}],relatedBattles:['hannibal']},
 {...carthage,id:'carthage-siege',from:-149,to:-147,focusYear:-149,period:'第三次布匿战争围城：前 149—147 年',polity:fact('迦太基与罗马再次开战，城市仍在抵抗；罗马围攻并不等于围城开始时已完成占领。'),reading:[{chapter:69,pages:[582,583]}]},
 {...carthage,id:'carthage-destroyed',from:-146,to:-146,period:'前 146 年攻陷之后',kind:'事件地点',polity:fact('按罗马攻陷并毁坏迦太基之后记录，布匿迦太基的独立政治中心终结；后来的罗马城市另属重建阶段。','carthageSite'),people:fact('课程叙述了杀戮与奴役。本条不采用未经进一步核对的全城人口总数，也不把城市毁坏解释为整个北非人口消失。'),reading:[{chapter:69,pages:[582,583]}],readingNote:'课程对“撒盐”使用“据说”。地图没有足够核对依据，不将这一细节作为已确认事件。'},
 {id:'rome-second-punic',placeId:'rome',title:'罗马',displayName:'Roma',from:-218,to:-202,focusYear:-218,period:'罗马共和国与第二次布匿战争：前 218—202 年',kind:'历史城市',polity:fact('罗马共和国的政治中心，与迦太基争夺地中海势力。战时的罗马已控制多种身份的领地和盟友，并非只是一座城市。'),territory:scale,people:fact('罗马公民、意大利盟邦居民与军队成员不能相互替代。军队在意大利作战，不代表当地居民拥有完全相同的公民权。'),language:unknownLanguage,nameNote:fact('罗马城和罗马共和国分别是地点与政治共同体；此时不能使用后来皇帝统治的制度名称。'),reading:[{chapter:69,pages:[579,581]}],related:['carthage','syracuse'],relatedBattles:['hannibal']},
 {id:'syracuse-expedition',placeId:'syracuse',title:'叙拉古',displayName:'Syrakousai / Syracuse',from:-415,to:-413,focusYear:-415,period:'雅典西西里远征：前 415—413 年',kind:'城邦',polity:fact('西西里东岸的希腊城邦，抵抗雅典远征。雅典舰队抵达、修筑围攻设施，不意味着叙拉古已加入雅典帝国。'),territory:scale,people:fact('希腊城邦位于今天的意大利境内。现代国界不能直接推导古代居民的政治身份。'),language:unknownLanguage,nameNote:fact('叙拉古对应现代锡拉库萨。西西里是岛屿名称，不是这一座城市的别名。'),reading:[{chapter:38,pages:[299,301]}],related:['athens','sparta','carthage'],relatedBattles:['sicily']},
];
