// Page numbers refer to the user-supplied PDF, counted from its first page.
export const courseDocument={title:'顾衡讲透欧洲史（不含加餐）',pages:2236,chapters:260,sha256:'913f657e7aed2079a6a96c93b63f259b2a60acf9e5b1bd4870a524a4993ec24b'};
export interface ReadingReference {chapter:number;pages:[number,number];note?:string}
export const courseSources={
 prum:{title:'莱茵地区历史门户：855 年中部王国再次分割',url:'https://www.rheinische-geschichte.lvr.de/chronicle/855'},
 carolingian:{title:'大都会博物馆：加洛林时代与查理曼',url:'https://www.metmuseum.org/essays/carolingian-art'},
 regensburg:{title:'德国 UNESCO 委员会：雷根斯堡与东法兰克宫廷',url:'https://www.unesco.de/staette/altstadt-von-regensburg-mit-stadtamhof/'},
 oviedo:{title:'西班牙文化部：奥维耶多与阿斯图里亚斯王国',url:'https://www.cultura.gob.es/cultura/areas/patrimonio/mc/patrimoniomundial/bienes-declarados/por-ano-de-inscripcion/1985/asturias.html'},
 abbasid:{title:'大都会博物馆：阿拔斯时期与两座都城',url:'https://www.metmuseum.org/essays/the-art-of-the-abbasid-period-750-1258'},
 samarra:{title:'UNESCO：萨迈拉考古城',url:'https://whc.unesco.org/en/list/276/'},
 ribemont:{title:'莱茵地区历史门户：880 年里伯蒙条约',url:'https://www.rheinische-geschichte.lvr.de/chronicle/880'},
 lotharingia:{title:'莱茵地区历史门户：法兰克分裂后的莱茵地区',url:'https://rheinische-geschichte.lvr.de/Epochen-und-Themen/Epochen/500-bis-785---die-rheinlande-im-fruehmittelalter/DE-2086/lido/57ab21f57328c2.42556102'},
 parisMedieval:{title:'巴黎市：中世纪的城市与地方权力',url:'https://www.paris.fr/pages/paris-des-carolingiens-aux-revolutionnaires-22384'},
 paviaItalian:{title:'帕维亚旅游局：意大利王国的加冕中心',url:'https://www.visitpavia.com/it/visitare-pavia/turismo-culturale-pavia/basilica-di-san-michele-maggiore'},
 italyEarly:{title:'大都会博物馆：意大利半岛 500—1000 年',url:'https://www.metmuseum.org/toah/ht/06/eust.html'},
 paviaEarly:{title:'帕维亚旅游局：伦巴第王都的遗产',url:'https://www.visitpavia.com/it/eredita-longobarda-di-pavia'},
 toledoEarly:{title:'UNESCO：托莱多历史城市',url:'https://whc.unesco.org/en/list/379/'},
 toledoChurch:{title:'托莱多总教区：西哥特王都与教会沿革',url:'https://www.architoledo.org/archidiocesis/historia/'},
 damascusEarly:{title:'UNESCO：大马士革古城',url:'https://whc.unesco.org/en/list/20/'},
 kairouanEarly:{title:'UNESCO：凯鲁万及 670 年建城',url:'https://whc.unesco.org/en/list/499/'},
 gregoryEarly:{title:'梵蒂冈：大格列高利、伦巴第人与罗马',url:'https://www.vatican.va/content/benedict-xvi/en/audiences/2008/documents/hf_ben-xvi_aud_20080528.html'},
 transitionEarly:{title:'大都会博物馆：拜占庭与伊斯兰的过渡时代',url:'https://www.metmuseum.org/exhibitions/listings/2012/byzantium-and-islam'},
 umayyadEarly:{title:'大都会博物馆：倭马亚时期（661—750）',url:'https://www.metmuseum.org/essays/the-art-of-the-umayyad-period-661-750'},
 trierLate:{title:'UNESCO：特里尔与晚期罗马皇帝驻地',url:'https://whc.unesco.org/en/list/367/'},
 galerius:{title:'希腊文化部：塞萨洛尼基伽列里乌斯宫殿',url:'https://galeriuspalace.culture.gr/'},
 toulouseLate:{title:'图卢兹圣雷蒙考古博物馆：罗马城市与西哥特王都',url:'https://saintraymond.toulouse.fr/en/the-permanent-tour/'},
 tournaiLate:{title:'图尔奈旅游局：希尔德里克与克洛维',url:'https://en.visittournai.be/exciting/tournai-berceau-clovis/'},
 lyonLate:{title:'里昂市档案馆：勃艮第统治与 534 年征服',url:'https://www.archives-lyon.fr/arrive-a-lyon'},
 africaLate:{title:'大都会博物馆：北非 1—500 年',url:'https://www.metmuseum.org/toah/ht/05/afw.html'},
 africaVandal:{title:'大都会博物馆：汪达尔与东罗马时期的北非',url:'https://www.metmuseum.org/toah/ht/06/afw.html'},
 britainLate:{title:'英国遗产保护机构：罗马统治如何在不列颠结束',url:'https://www.english-heritage.org.uk/visit/inspire-me/why-did-the-romans-leave-britain/'},
 verdun:{title:'莱茵地区历史门户：843 年凡尔登条约',url:'https://www.rheinische-geschichte.lvr.de/chronicle/843'},
 william:{title:'英国皇家宫殿管理机构：征服者威廉',url:'https://www.hrp.org.uk/tower-of-london/history-and-stories/william-the-conqueror/'},
 jerusalemCoords:{title:'联合国教科文组织：耶路撒冷古城定位',url:'https://whc.unesco.org/en/list/148/maps'},
 jerusalemMedieval:{title:'大都会博物馆：中世纪耶路撒冷的居民与征服',url:'https://www.metmuseum.org/exhibitions/listings/2016/jerusalem/exhibition-galleries'},
 crusades:{title:'大都会博物馆：十字军东征',url:'https://www.metmuseum.org/essays/the-crusades-1095-1291'},
 seleucid:{title:'大都会博物馆：塞琉古帝国',url:'https://www.metmuseum.org/essays/the-seleucid-empire-323-64-b-c'},
 antiochHistory:{title:'伊朗百科全书：奥龙特斯河畔的安条克',url:'https://www.iranicaonline.org/articles/antioch-1-northern-syria/'},
 zamaTreaty:{title:'波利比乌斯《历史》15.18：战后和约条款',url:'https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0234%3Abook%3D15%3Achapter%3D18'},
 sardisHistory:{title:'萨迪斯考古队：城市沿革与古代名称',url:'https://sardisexpedition.org/en/essays/about-sardis'},
 sardisCoords:{title:'UNESCO：萨迪斯遗址定位',url:'https://whc.unesco.org/en/list/1731/maps'},
 babylonCoords:{title:'Pleiades：巴比伦遗址与名称',url:'https://pleiades.stoa.org/places/893951'},
 persia:{title:'大都会博物馆：阿契美尼德波斯帝国',url:'https://www.metmuseum.org/essays/the-achaemenid-persian-empire-550-330-b-c'},
 alexander:{title:'大都会博物馆：马其顿崛起与亚历山大征服',url:'https://www.metmuseum.org/essays/the-rise-of-macedonia-and-the-conquests-of-alexander-the-great'},
 ptolemaic:{title:'大都会博物馆：托勒密时期的埃及',url:'https://www.metmuseum.org/essays/egypt-in-the-ptolemaic-period'},
 pergamon:{title:'UNESCO：帕加马与阿塔罗斯王朝',url:'https://whc.unesco.org/en/list/1457/'},
 pergamonCoords:{title:'UNESCO：帕加马古城定位',url:'https://whc.unesco.org/en/list/1457/maps'},
 carthageSite:{title:'UNESCO：迦太基遗址及布匿、罗马时期',url:'https://whc.unesco.org/en/list/37/'},
 byzantine:{title:'大都会博物馆：拜占庭的历史分期',url:'https://www.metmuseum.org/essays/byzantium-ca-330-1453'},
 ravenna:{title:'艾米利亚-罗马涅大区：拉文纳历史',url:'https://turismo.emilia-romagna.it/ravenna/'},
 ravennaArt:{title:'UNESCO：拉文纳早期基督教古迹',url:'https://whc.unesco.org/en/list/788/'},
 izmit:{title:'土耳其文化旅游部：伊兹米特',url:'https://kocaeli.ktb.gov.tr/TR-174635/izmit.html'},
 nicomedia:{title:'Pleiades：Nicomedia',url:'https://pleiades.stoa.org/places/511337'},
 aachen:{title:'亚琛市：查理曼的宫廷驻地',url:'https://www.aachen.de/in-aachen-leben/kultur/geschichte/die-aachener-chronoskope/'},
 aachenSite:{title:'UNESCO：亚琛大教堂与定位',url:'https://whc.unesco.org/en/list/3/'},
 cordoba:{title:'UNESCO：科尔多瓦哈里发国与历史中心',url:'https://whc.unesco.org/en/list/313/'},
 umayyad:{title:'大都会博物馆：伊比利亚的倭马亚时代',url:'https://www.metmuseum.org/essays/the-art-of-the-umayyad-period-in-spain-711-1031'},
 avignon:{title:'UNESCO：阿维尼翁历史中心',url:'https://whc.unesco.org/en/list/228/'},
 avignonHistory:{title:'ICOMOS：阿维尼翁历史评估',url:'https://whc.unesco.org/document/153008'},
 granada:{title:'阿尔罕布拉宫管理局：格拉纳达战争',url:'https://www.alhambra-patronato.es/elemento-del-mes/la-guerra-de-granada-muley-hacen-y-boabdil'},
 granadaSite:{title:'UNESCO：格拉纳达古迹与定位',url:'https://whc.unesco.org/en/list/314/'},
 luther:{title:'Deutschlandmuseum：1517 年九十五条论纲',url:'https://www.deutschlandmuseum.de/en/history/calendar/1517-10-31-95-theses/'},
 theses:{title:'路德九十五条论纲（拉丁文）',url:'https://www.luther.de/en/95th-lat.html'},
 wittenberg:{title:'UNESCO：维滕贝格城堡教堂定位',url:'https://whc.unesco.org/en/list/783/maps'},
 prague:{title:'捷克总统府：布拉格城堡与 1618 年事件',url:'https://www.hrad.cz/file/edee/2024/11/en_state-rooms-of-the-prague-castle-20241125-142758.pdf'},
 norman:{title:'英国皇家宫殿管理机构：诺曼征服后的伦敦塔',url:'https://www.hrp.org.uk/tower-of-london/history-and-stories/the-story-of-the-tower-of-london/'},
 civilwar:{title:'英国议会：1642 年内战及议会阵营',url:'https://www.parliament.uk/about/living-heritage/evolutionofparliament/parliamentaryauthority/civilwar/overview/presbyterians/'},
 civilPeople:{title:'英国国家档案馆：内战中的女性',url:'https://www.nationalarchives.gov.uk/education/resources/women-english-civil-wars/'},
 cityCoordinates:{title:'Natural Earth：现代城市代表坐标',url:'https://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-populated-places/'},
} as const;
