// Page numbers refer to the user-supplied PDF, counted from its first page.
export const courseDocument={title:'顾衡讲透欧洲史（不含加餐）',pages:2236,chapters:260,sha256:'913f657e7aed2079a6a96c93b63f259b2a60acf9e5b1bd4870a524a4993ec24b'};
export interface ReadingReference {chapter:number;pages:[number,number];note?:string}
export const courseSources={
 verdun:{title:'莱茵地区历史门户：843 年凡尔登条约',url:'https://www.rheinische-geschichte.lvr.de/chronicle/843'},
 william:{title:'英国皇家宫殿管理机构：征服者威廉',url:'https://www.hrp.org.uk/tower-of-london/history-and-stories/william-the-conqueror/'},
 jerusalemCoords:{title:'联合国教科文组织：耶路撒冷古城定位',url:'https://whc.unesco.org/en/list/148/maps'},
 jerusalemMedieval:{title:'大都会博物馆：中世纪耶路撒冷的居民与征服',url:'https://www.metmuseum.org/exhibitions/listings/2016/jerusalem/exhibition-galleries'},
 crusades:{title:'大都会博物馆：十字军东征',url:'https://www.metmuseum.org/essays/the-crusades-1095-1291'},
 seleucid:{title:'大都会博物馆：塞琉古帝国',url:'https://www.metmuseum.org/essays/the-seleucid-empire-323-64-b-c'},
 antiochHistory:{title:'伊朗百科全书：奥龙特斯河畔的安条克',url:'https://www.iranicaonline.org/articles/antioch-1-northern-syria/'},
 zamaTreaty:{title:'波利比乌斯《历史》15.18：战后和约条款',url:'https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.01.0234%3Abook%3D15%3Achapter%3D18'},
 sardisHistory:{title:'萨迪斯考古队：城市沿革与古代名称',url:'https://sardisexpedition.org/en/essays/about-sardis'},
 sardisCoords:{title:'UNESCO：萨迪斯遗址定位',url:'https://whc.unesco.org/en/list/1731/maps'},
 babylonCoords:{title:'Pleiades：巴比伦遗址与名称',url:'https://pleiades.stoa.org/places/893951'},
 persia:{title:'大都会博物馆：阿契美尼德波斯帝国',url:'https://www.metmuseum.org/essays/the-achaemenid-persian-empire-550-330-b-c'},
 alexander:{title:'大都会博物馆：马其顿崛起与亚历山大征服',url:'https://www.metmuseum.org/essays/the-rise-of-macedonia-and-the-conquests-of-alexander-the-great'},
 ptolemaic:{title:'大都会博物馆：托勒密时期的埃及',url:'https://www.metmuseum.org/essays/egypt-in-the-ptolemaic-period'},
 pergamon:{title:'UNESCO：帕加马与阿塔罗斯王朝',url:'https://whc.unesco.org/en/list/1457/'},
 pergamonCoords:{title:'UNESCO：帕加马古城定位',url:'https://whc.unesco.org/en/list/1457/maps'},
 carthageSite:{title:'UNESCO：迦太基遗址及布匿、罗马时期',url:'https://whc.unesco.org/en/list/37/'},
 byzantine:{title:'大都会博物馆：拜占庭的历史分期',url:'https://www.metmuseum.org/essays/byzantium-ca-330-1453'},
 ravenna:{title:'艾米利亚-罗马涅大区：拉文纳历史',url:'https://turismo.emilia-romagna.it/ravenna/'},
 ravennaArt:{title:'UNESCO：拉文纳早期基督教古迹',url:'https://whc.unesco.org/en/list/788/'},
 izmit:{title:'土耳其文化旅游部：伊兹米特',url:'https://kocaeli.ktb.gov.tr/TR-174635/izmit.html'},
 nicomedia:{title:'Pleiades：Nicomedia',url:'https://pleiades.stoa.org/places/511337'},
 aachen:{title:'亚琛市：查理曼的宫廷驻地',url:'https://www.aachen.de/in-aachen-leben/kultur/geschichte/die-aachener-chronoskope/'},
 aachenSite:{title:'UNESCO：亚琛大教堂与定位',url:'https://whc.unesco.org/en/list/3/'},
 cordoba:{title:'UNESCO：科尔多瓦哈里发国与历史中心',url:'https://whc.unesco.org/en/list/313/'},
 umayyad:{title:'大都会博物馆：伊比利亚的倭马亚时代',url:'https://www.metmuseum.org/essays/the-art-of-the-umayyad-period-in-spain-711-1031'},
 avignon:{title:'UNESCO：阿维尼翁历史中心',url:'https://whc.unesco.org/en/list/228/'},
 avignonHistory:{title:'ICOMOS：阿维尼翁历史评估',url:'https://whc.unesco.org/document/153008'},
 granada:{title:'阿尔罕布拉宫管理局：格拉纳达战争',url:'https://www.alhambra-patronato.es/elemento-del-mes/la-guerra-de-granada-muley-hacen-y-boabdil'},
 granadaSite:{title:'UNESCO：格拉纳达古迹与定位',url:'https://whc.unesco.org/en/list/314/'},
 luther:{title:'Deutschlandmuseum：1517 年九十五条论纲',url:'https://www.deutschlandmuseum.de/en/history/calendar/1517-10-31-95-theses/'},
 theses:{title:'路德九十五条论纲（拉丁文）',url:'https://www.luther.de/en/95th-lat.html'},
 wittenberg:{title:'UNESCO：维滕贝格城堡教堂定位',url:'https://whc.unesco.org/en/list/783/maps'},
 prague:{title:'捷克总统府：布拉格城堡与 1618 年事件',url:'https://www.hrad.cz/file/edee/2024/11/en_state-rooms-of-the-prague-castle-20241125-142758.pdf'},
 norman:{title:'英国皇家宫殿管理机构：诺曼征服后的伦敦塔',url:'https://www.hrp.org.uk/tower-of-london/history-and-stories/the-story-of-the-tower-of-london/'},
 civilwar:{title:'英国议会：1642 年内战及议会阵营',url:'https://www.parliament.uk/about/living-heritage/evolutionofparliament/parliamentaryauthority/civilwar/overview/presbyterians/'},
 civilPeople:{title:'英国国家档案馆：内战中的女性',url:'https://www.nationalarchives.gov.uk/education/resources/women-english-civil-wars/'},
 cityCoordinates:{title:'Natural Earth：现代城市代表坐标',url:'https://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-populated-places/'},
} as const;
