import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,Check,Compass,Globe2,Layers,LocateFixed,Mountain,Pause,Play,Search,Share2,X,Menu,MapPin,Flag,Clock3} from 'lucide-react';
import {GreekMap,type AtlasOverlay,type Camera,type MapAtlas,type MapCommand} from '../greek/GreekMap';
import {boundarySnapshots} from '../atlas-data/historical-boundaries';
import {EMPTY,HISTORY_SOURCE,MODERN_SOURCE,allBattles,ancientPlaces,geographicPlaces,battleYears,eras,centuryGuides,makeAreas,modernPlaces,parseYear,placeContext,placeLabel,snapshotFor,translate,yearLabel,type Area,type GazetteerPlace} from './model';
import {europeLandforms,geographyTours} from './geography';
import '../greek/greek.css';
import '../greek/terrain-theme.css';
import './europe.css';
import './maps-ui.css';
import {historicalDetail,detailsAt,historyWindows,alignmentAt} from './history-details';
import {coursePlaces,courseDetails} from './course-details';
import {courseDocument} from './course-sources';
import {HistoryDetailCard,HistoryPeriods} from './HistoryDetailCard';
import {LateAntiquityGuide} from './LateAntiquityGuide';

import {easternSuccessors} from './eastern-context';
import {EasternEmpire,easternRegions,easternAreaNames} from './EasternEmpire';
import {WesternEmpire,westernRegions} from './WesternEmpire';

type Tab='time'|'places'|'events'|'geography';
const none:string[]=[];
async function json(url:string):Promise<GeoJSON.FeatureCollection>{const r=await fetch(url);if(!r.ok)throw new Error(`资料未能加载 (${r.status})`);const data=await r.json();if(data.type!=='FeatureCollection')throw new Error('资料格式不符');return data;}
function initial(){const q=new URLSearchParams(location.search);const battle=allBattles.find(b=>b.id===q.get('battle'));return {year:parseYear(q.get('year')??'100')??100,modern:q.get('mode')==='modern',place:q.get('place')??undefined,battle,step:battle?Math.max(0,Math.min(battle.stages.length-1,Math.floor(Number(q.get('stage'))||0))):0};}
export function EuropeApp(){
 const [start]=useState(initial);
 const [empireOpen,setEmpireOpen]=useState(new URLSearchParams(location.search).get('empire')==='western-rome'||new URLSearchParams(location.search).get('empire')==='eastern-rome');
 const [empireKind,setEmpireKind]=useState<'western-rome'|'eastern-rome'>(new URLSearchParams(location.search).get('empire')==='eastern-rome'?'eastern-rome':'western-rome');
 const topicRegions=empireKind==='eastern-rome'?[...easternRegions,...easternSuccessors]:westernRegions;
 const EmpireCard=empireKind==='eastern-rome'?EasternEmpire:WesternEmpire;
 const [empireRegion,setEmpireRegion]=useState<string>();
 const [year,setYear]=useState(start.year),[yearInput,setYearInput]=useState(String(start.year)),[modern,setModern]=useState(start.modern);
 const [tab,setTab]=useState<Tab>(start.battle?'events':start.place?'places':'time'),[selected,setSelected]=useState<string|undefined>(start.place),[selectedArea,setSelectedArea]=useState<string>();
 const [battle,setBattle]=useState(start.battle),[step,setStep]=useState(start.step),[playing,setPlaying]=useState(false);
 const [query,setQuery]=useState(''),[threeD,setThreeD]=useState(false),[areasOn,setAreasOn]=useState(true),[references,setReferences]=useState(false),[riversOn,setRiversOn]=useState(true),[pinsOn,setPinsOn]=useState(true);
 const [searchActive,setSearchActive]=useState(false),[layersOpen,setLayersOpen]=useState(false);
 const [command,setCommand]=useState<MapCommand>({ids:start.place?[start.place]:[],nonce:0,coordinates:empireOpen?(empireKind==='eastern-rome'?[[6,22],[45,47]]:[[-10,28],[23,56]]):undefined});
 const [message,setMessage]=useState(''),[sourceOpen,setSourceOpen]=useState(false),[mobilePanel,setMobilePanel]=useState(!!start.place||new URLSearchParams(location.search).has('empire'));
 const [geo,setGeo]=useState<{countries:GeoJSON.FeatureCollection;rivers:GeoJSON.FeatureCollection;places:GazetteerPlace[]}>();
 const [geoError,setGeoError]=useState(''),[retry,setRetry]=useState(0);
 const [historical,setHistorical]=useState<{key:string;data?:GeoJSON.FeatureCollection;error?:string}>({key:''});
 const dialog=useRef<HTMLDialogElement>(null),panelBody=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(panelBody.current)panelBody.current.scrollTop=0},[selected,selectedArea,tab]);
 const snapshot=modern?undefined:snapshotFor(year),key=snapshot?.filename??'';
 useEffect(()=>{let alive=true;setGeoError('');Promise.all([json('/europe-reference/ne_50m_admin_0_countries.geojson'),json('/europe-reference/ne_50m_rivers_lake_centerlines.geojson'),json('/europe-reference/ne_50m_populated_places.geojson')]).then(([countries,rivers,places])=>{if(alive)setGeo({countries,rivers,places:modernPlaces(places)})}).catch(()=>{if(alive)setGeoError('现代参考地理未能加载，请重试。')});return()=>{alive=false}},[retry]);
 useEffect(()=>{let alive=true;if(!key){setHistorical({key:''});return;}setHistorical({key});json(`/historical-boundaries/${key}`).then(data=>{if(alive)setHistorical({key,data})}).catch(()=>{if(alive)setHistorical({key,error:'这个年代的边界资料未能加载，请重试。'})});return()=>{alive=false}},[key,retry]);
 const allAreas=useMemo(()=>makeAreas(modern?geo?.countries??EMPTY:historical.key===key?historical.data??EMPTY:EMPTY,modern),[modern,geo,historical,key]);
 const drawnAreas=useMemo(()=>allAreas.filter(a=>(a.kind==='polity'||references)&&(modern||year<476||a.original!=='Western Roman Empire')&&(modern||year<1453||!easternAreaNames.includes(a.original))),[allAreas,references,modern,year]);
 const area=allAreas.find(a=>a.id===selectedArea);
 const allPlaces=useMemo(()=>[...geographicPlaces,...ancientPlaces,...(geo?.places??[]).filter(p=>!ancientPlaces.some(a=>Math.abs(a.coords[0]-p.coords[0])<.12&&Math.abs(a.coords[1]-p.coords[1])<.12))],[geo]);
 const place=allPlaces.find(p=>p.id===selected);
 const context=place&&!modern?placeContext(place.id,year):undefined;
 const detail=place&&!modern?historicalDetail(place.id,year):undefined;
 const activeDetails=useMemo(()=>modern?[]:detailsAt(year),[year,modern]);
 const normalized=query.trim().toLocaleLowerCase();
 const matchingPlaces=useMemo(()=>allPlaces.filter(p=>[p.name,p.modern,...p.aliases,...(!modern?[placeLabel(p,year),historicalDetail(p.id,year)?.polity.text??'']:[])].some(v=>v.toLocaleLowerCase().includes(normalized))).sort((a,b)=>Number(b.name===query)-Number(a.name===query)).slice(0,20),[allPlaces,normalized,query,year,modern]);
 const matchingAreas=drawnAreas.filter(a=>[a.name,a.original,translate(a.subject)].some(n=>n.toLocaleLowerCase().includes(normalized))).sort((a,b)=>Number(b.name.toLocaleLowerCase()===normalized)-Number(a.name.toLocaleLowerCase()===normalized));
 const visiblePlaces=useMemo(()=>pinsOn?(modern?allPlaces:[...ancientPlaces.filter(p=>!activeDetails.length||activeDetails.some(d=>d.placeId===p.id)||p.id===place?.id),...(place&&!ancientPlaces.some(p=>p.id===place.id)?[place]:[])]):(place?[place]:[]),[pinsOn,allPlaces,place,modern,activeDetails]);
 const atlas=useMemo<MapAtlas>(()=>({places:visiblePlaces.map(p=>({...p,color:modern?undefined:alignmentAt(p.id,year)?.color,name:placeLabel(p,year,modern)})),terrainPrefix:'europe-terrain',surfacePrefix:'europe-surface',bounds:[-25,24,55,72],maxzoom:7,center:[10.5633548,46.246345],zoom:4.2,pitch:42,bearing:0,minZoom:1.4,detailInSidebar:true,extent:[[-90,-30],[110,85]],landforms:europeLandforms,presets:['alps','north-plain','mediterranean'].map(id=>europeLandforms.find(p=>p.id===id)!),attribution:'历史区域：A. Ourednik 等（GPL-3.0）· 地点：Pleiades（CC BY 3.0）/ Natural Earth（公有领域）· 新增地点定位：UNESCO / Pleiades / Natural Earth',title:'欧洲时空地图 · 3D 地形与历史参考',theme:'light'}),[visiblePlaces,modern,year]);
 const overlay=useMemo<AtlasOverlay>(()=>({areas:areasOn&&!battle?{type:'FeatureCollection',features:drawnAreas.map(a=>a.feature)}:EMPTY,rivers:riversOn?geo?.rivers??EMPTY:EMPTY,labels:areasOn&&!battle?[...(empireOpen&&!modern?topicRegions.filter(r=>!('from' in r)||('to' in r&&year>=Number(r.from)&&year<=Number(r.to))).map(r=>({id:'region:'+r.id,name:r.name,coords:r.coords,color:'#77512f'})):[]),...drawnAreas.map(a=>({id:a.id,name:a.name,coords:a.coords,color:a.color}))]:[]}),[areasOn,battle,drawnAreas,riversOn,geo,empireOpen,modern,topicRegions,year]);
 const move=useCallback((ids:string[]=[],camera?:Camera,coordinates?:[number,number][])=>setCommand(c=>({ids,nonce:c.nonce+1,camera,coordinates})),[]);
 const onCamera=useCallback(()=>{},[]);
 useEffect(()=>{if(place&&selected===start.place){if(place.viewBounds)move([],undefined,place.viewBounds);else move([place.id])}},[place?.id,move,start.place]);
 function closeBattle(){setBattle(undefined);setPlaying(false);setStep(0)}
 function chooseYear(value:number){setYear(value);setYearInput(String(value));setModern(false);setSelectedArea(undefined);closeBattle();}
 function openEmpire(kind:'western-rome'|'eastern-rome'='western-rome'){setEmpireKind(kind);setEmpireRegion(undefined);setEmpireOpen(true);setSelected(undefined);setSelectedArea(undefined);setModern(false);closeBattle();setQuery('');setSearchActive(false);setTab('time');setMobilePanel(true);move([],undefined,kind==='eastern-rome'?[[6,22],[45,47]]:[[-10,28],[23,56]]);}
 function chooseModern(){setEmpireOpen(false);setModern(true);setSelectedArea(undefined);closeBattle();}
 const selectPlace=useCallback((id:string)=>{setEmpireOpen(false);setSelected(id);setSelectedArea(undefined);setBattle(undefined);setPlaying(false);setQuery('');setSearchActive(false);setTab('places');const region=geographicPlaces.find(p=>p.id===id);if(region?.viewBounds)move([],undefined,region.viewBounds);else move([id]);setMobilePanel(true)},[move]);
 function selectArea(id:string){if(id.startsWith('region:')){const r=topicRegions.find(r=>r.id===id.slice(7));if(r){setEmpireRegion(r.id);setMobilePanel(true);move([],undefined,r.bounds)}return;}const p=allAreas.find(a=>a.id===id);if(!p)return;setEmpireOpen(!modern&&(p.original==='Western Roman Empire'||easternAreaNames.includes(p.original)));setEmpireKind(easternAreaNames.includes(p.original)?'eastern-rome':'western-rome');setEmpireRegion(undefined);setSelectedArea(id);setSelected(undefined);setSearchActive(false);setQuery('');setTab('time');setMobilePanel(true);}
 function focusArea(a:Area){selectArea(a.id);move([],undefined,a.bounds);}
 function pickBattle(id:string){setEmpireOpen(false);const b=allBattles.find(v=>v.id===id);if(!b)return;setBattle(b);setStep(0);setPlaying(false);setSelected(undefined);setSelectedArea(undefined);setSearchActive(false);setQuery('');setMobilePanel(false);setTab('events');setModern(false);const y=battleYears[id];setYear(y);setYearInput(String(y));}
 function openPanel(value:Tab){setEmpireOpen(false);setTab(value);setMobilePanel(true);setSearchActive(false);setQuery('');setSelected(undefined);setSelectedArea(undefined);}
 const matchingBattles=allBattles.filter(b=>[b.title,b.question,b.period].some(t=>t.toLocaleLowerCase().includes(normalized)));
 const empireMatch=!modern&&(!normalized||'西罗马帝国 western roman empire'.includes(normalized));
 const easternMatch=!modern&&(!normalized||'东罗马帝国 拜占庭帝国 eastern roman empire byzantine empire'.includes(normalized));
 function submitSearch(){if(easternMatch&&normalized){openEmpire('eastern-rome');return;}if(empireMatch&&normalized)openEmpire();else if(matchingPlaces[0])selectPlace(matchingPlaces[0].id);else if(matchingAreas[0])focusArea(matchingAreas[0]);else if(matchingBattles[0])pickBattle(matchingBattles[0].id);}
 useEffect(()=>{if(battle)move([],undefined,battle.stages[step].path)},[battle,step,move]);
 useEffect(()=>{if(!playing||!battle)return;const t=setTimeout(()=>{if(step>=battle.stages.length-1)setPlaying(false);else setStep(v=>v+1)},4200);return()=>clearTimeout(t)},[playing,battle,step]);
 useEffect(()=>{document.title='欧洲时空地图 · 在地图上读懂欧洲';const u=new URL(location.href);u.search='';u.searchParams.set('year',String(year));if(modern)u.searchParams.set('mode','modern');if(empireOpen)u.searchParams.set('empire',empireKind);if(selected)u.searchParams.set('place',selected);if(battle){u.searchParams.set('battle',battle.id);u.searchParams.set('stage',String(step))}history.replaceState(null,'',u)},[year,modern,selected,battle,step,empireOpen,empireKind]);
 useEffect(()=>{if(sourceOpen)dialog.current?.showModal();else dialog.current?.close()},[sourceOpen]);
 useEffect(()=>{if(!message)return;const timer=setTimeout(()=>setMessage(''),5000);return()=>clearTimeout(timer)},[message]);
 async function share(){try{await navigator.clipboard.writeText(location.href);setMessage('地图链接已复制。当前为本机预览，公开发布后大家才能访问。')}catch{setMessage('复制未成功，可以直接复制浏览器地址栏。')}}
 const currentStage=battle?.stages[step];
 const status=modern?'现代参考 · Natural Earth v5.1.1':snapshot?`${yearLabel(snapshot.year)}资料 · 历史概览待核对`:'这个年份的疆界尚未收录';
 const loading=modern?!geo:!!key&&(historical.key!==key||(!historical.data&&!historical.error));
 const historyError=historical.key===key?historical.error:undefined;
 const snapshotIndex=snapshot?boundarySnapshots.indexOf(snapshot):0;
 return <main className={`g-app e-app maps-ui ${mobilePanel?'panel-open':''} ${battle?'route-open':''} ${searchActive?'is-searching':''}`}>
  <nav className="m-rail" aria-label="地图导航">
   <button className="m-rail-menu" onClick={()=>mobilePanel?setMobilePanel(false):openPanel('time')} aria-label={mobilePanel?'收起导航详情':'打开导航详情'}><Menu size={21}/></button>
   {([{id:'time',label:'年代',Icon:Clock3},{id:'places',label:'地点',Icon:MapPin},{id:'events',label:'战役',Icon:Flag},{id:'geography',label:'地形',Icon:Mountain}] as const).map(({id,label,Icon})=><button key={id} className={mobilePanel&&tab===id&&!searchActive?'active':''} aria-pressed={mobilePanel&&tab===id&&!searchActive} onClick={()=>openPanel(id)}><span><Icon size={21}/></span>{label}</button>)}
   <button className="m-rail-source" aria-label="资料与覆盖" onClick={()=>setSourceOpen(true)}><span><BookOpen size={21}/></span>资料</button>
  </nav>
  <header className="m-searchbar"><button className="m-menu" onClick={()=>mobilePanel?setMobilePanel(false):openPanel('time')} aria-label={mobilePanel?'收起探索面板':'打开探索面板'} aria-expanded={mobilePanel}><Menu size={22}/></button><form role="search" onSubmit={e=>{e.preventDefault();submitSearch()}}><input aria-label="搜索地点、政权或战役" placeholder="搜索地点、政权或战役" value={query} onFocus={()=>{setSearchActive(true);setMobilePanel(true)}} onChange={e=>{setQuery(e.target.value);setSearchActive(true);setMobilePanel(true)}} onKeyDown={e=>{if(e.key==='Escape'){setSearchActive(false);setMobilePanel(false)}}}/>{query?<button type="button" aria-label="清空搜索" onClick={()=>{setQuery('');setSearchActive(true)}}><X size={20}/></button>:<button type="submit" aria-label="搜索"><Search size={21}/></button>}</form><button className="m-search-help" aria-label="资料与覆盖" onClick={()=>setSourceOpen(true)}><BookOpen size={20}/></button></header>
  <nav className="m-chips" aria-label="地图快捷入口"><button className={mobilePanel&&tab==='time'&&!searchActive?'active':''} onClick={()=>openPanel('time')}><Clock3 size={16}/>历史年代</button><button className={mobilePanel&&tab==='places'&&!searchActive?'active':''} onClick={()=>openPanel('places')}><MapPin size={16}/>地点</button><button className={mobilePanel&&tab==='events'&&!searchActive?'active':''} onClick={()=>openPanel('events')}><Flag size={16}/>战役路线</button><button className={mobilePanel&&tab==='geography'&&!searchActive?'active':''} onClick={()=>openPanel('geography')}><Mountain size={16}/>山川地形</button></nav>
  <div className="m-top-actions"><button onClick={share} aria-label="复制当前地图链接"><Share2 size={19}/></button></div>
  <div className="e-workspace">
   <aside className={`e-sidebar ${mobilePanel?'is-open':''}`} aria-label="地图探索面板" aria-hidden={!mobilePanel} inert={!mobilePanel}><div className="m-panel-heading"><h1>{searchActive?(normalized?'搜索结果':'探索欧洲'):empireOpen?'帝国与历史地区':area?'区域详情':place?'地点详情':({time:'历史年代',places:'地点索引',events:'战役路线',geography:'山川地形'})[tab]}</h1><button onClick={()=>setMobilePanel(false)} aria-label="关闭详情面板"><X size={20}/></button></div>
    <div className="e-panel" ref={panelBody}>
    {searchActive&&<div className="m-search-results">{easternMatch&&<button onClick={()=>openEmpire('eastern-rome')}><Globe2 size={19}/><span><strong>东罗马帝国（拜占庭）</strong><small>330／395—1453 年 · 地区得失与帝国延续</small></span><ArrowRight size={16}/></button>}{empireMatch&&<button onClick={()=>openEmpire()}><Globe2 size={19}/><span><strong>西罗马帝国</strong><small>395—476 年 · 组成地区与后继政权</small></span><ArrowRight size={16}/></button>}{!normalized&&<p className="e-note">输入书里的古名、今名或事件名称，直接在地图上找到它。</p>}{matchingPlaces.length>0&&<><p className="e-section-title">地点{normalized?` · 显示 ${Math.min(6,matchingPlaces.length)} 个结果`:''}</p>{matchingPlaces.slice(0,6).map(p=><button key={p.id} onClick={()=>selectPlace(p.id)}><MapPin size={19}/><span><strong>{placeLabel(p,year,modern)}</strong><small>{p.modern}</small></span><ArrowRight size={16}/></button>)}</>}{matchingAreas.length>0&&<><p className="e-section-title">{modern?'现代参考区域':`${yearLabel(year)} · 参考区域`}</p>{matchingAreas.slice(0,5).map(a=><button key={a.id} onClick={()=>focusArea(a)}><Globe2 size={19}/><span><strong>{a.name}</strong><small>{a.kind==='polity'?'政权类参考':'文化或其他区域'}</small></span><ArrowRight size={16}/></button>)}</>}{matchingBattles.length>0&&<><p className="e-section-title">战役路线</p>{matchingBattles.slice(0,4).map(b=><button key={b.id} onClick={()=>pickBattle(b.id)}><Flag size={19}/><span><strong>{b.title}</strong><small>{b.period}</small></span><ArrowRight size={16}/></button>)}</>}{!easternMatch&&!empireMatch&&!matchingPlaces.length&&!matchingAreas.length&&!matchingBattles.length&&<div className="m-empty"><Search size={28}/><h2>没有找到“{query}”</h2><p>试试其他译名、英文名，或切换历史年代。</p></div>}</div>}
    {!searchActive&&tab==='time'&&<>
     {empireOpen&&!modern?<EmpireCard year={year} selected={empireRegion} onYear={chooseYear} onRegion={(id,coords)=>{setEmpireRegion(id);move([],undefined,coords)}} onCity={selectPlace} onClose={()=>{setEmpireOpen(false);setSelectedArea(undefined)}}/>:area?<article className="e-detail"><button className="e-back" onClick={()=>setSelectedArea(undefined)}>← 返回时代概览</button><small>{modern?'现代参考区域':'历史参考区域'}</small><h2>{area.name}</h2><details><summary>原资料名称</summary><p>{area.original}</p></details><dl><dt>资料年代</dt><dd>{modern?'Natural Earth v5.1.1':snapshot&&yearLabel(snapshot.year)}</dd><dt>原资料归属</dt><dd>{translate(area.subject)}</dd><dt>区域类别</dt><dd>{area.kind==='polity'?'政权类参考':'文化或其他参考区域'}</dd></dl><p>{area.kind==='polity'?'这块颜色帮助辨认政治空间。参考边界仍需进一步核对，放大地图不会增加史料精度。':'原始资料把这一名称作为区域记录；它不代表统一国家，也不是精确居民分布。'}</p>{!modern&&<p className="e-note">疆界不能说明所有居民的族群、语言或身份；这些资料需要分别记录。</p>}<button className="e-primary" onClick={()=>move([],undefined,area.bounds)}>查看区域范围 <ArrowRight size={14}/></button><a href={area.source} target="_blank" rel="noreferrer">查看区域资料 ↗</a></article>:<>
      {!normalized&&<>{!modern&&<LateAntiquityGuide year={year} onPlace={selectPlace} onYear={chooseYear}/>}<div className="h-overview"><button className="e-tour" onClick={()=>openEmpire()}><Globe2 size={18}/><span><strong>西罗马帝国由哪些地区组成？</strong><small>395—476 年 · 六个地区与后来的去向</small></span><ArrowRight size={14}/></button><button className="e-tour" onClick={()=>openEmpire('eastern-rome')}><Globe2 size={18}/><span><strong>东罗马帝国由哪些地区组成？</strong><small>八个历史地区 · 从新罗马到君士坦丁堡陷落</small></span><ArrowRight size={14}/></button><strong>百年级空间骨架</strong><p className="e-note">先用每百年的锚点认识版图、主要居民与语言，再进入下方的具体资料年份。</p><div className="h-window-buttons">{centuryGuides.map(w=><button key={w.year} className={year===w.year&&!modern?"active":""} title={w.people} onClick={()=>{chooseYear(w.year);const coords=detailsAt(w.year).flatMap(d=>{const p=allPlaces.find(p=>p.id===d.placeId);return p?[p.coords]:[]});move([],undefined,coords)}}>{yearLabel(w.year)}<span>{w.title}<small>{w.hint}</small></span></button>)}</div><strong>有详细资料的年代</strong><div className="h-window-buttons">{historyWindows.map(w=><button key={w.year} className={year===w.year&&!modern?"active":""} onClick={()=>{chooseYear(w.year);const coords=detailsAt(w.year).flatMap(d=>{const p=allPlaces.find(p=>p.id===d.placeId);return p?[p.coords]:[]});move([],undefined,coords)}}>{yearLabel(w.year)}<span>{w.title}</span></button>)}</div>{activeDetails.length>0&&<><p>此时段有 {activeDetails.length} 处详细资料。地图默认突出这些地点；其余地点仍可搜索。</p><div className="h-site-links">{activeDetails.map(d=><button key={d.id} onClick={()=>selectPlace(d.placeId)}>{d.title}<span>{d.kind}</span></button>)}</div></>}</div><p className="e-section-title">其他时代概览</p><div className="e-eras">{eras.map(e=><button key={e.year} className={!modern&&year===e.year?'active':''} onClick={()=>chooseYear(e.year)}><span>{e.year<0?'前 ':''}{Math.abs(e.year)}</span><strong>{e.title}</strong><ArrowRight size={13}/></button>)}<button className={modern?'active':''} onClick={chooseModern}><span>今</span><strong>现代地理参考</strong><ArrowRight size={13}/></button></div></>}
      <p className="e-section-title">{modern?'参考区域':'本时点政权类参考'} · {matchingAreas.filter(a=>a.kind==='polity').length}</p><div className="e-area-list">{matchingAreas.map(a=><button key={a.id} onClick={()=>focusArea(a)}><i style={{background:a.color}}/><span>{a.name}{a.kind==='reference'&&<small>文化或其他区域</small>}</span><ArrowRight size={12}/></button>)}</div>
      {!loading&&!matchingAreas.length&&<p className="e-note">{snapshot||modern?'没有匹配的已收录区域。':'此年份暂无边界资料。地点与地形仍可查询。'}</p>}
     </>}
    </>}
    {!searchActive&&tab==='places'&&<>{place?(place.kind==='地理区域'?<article className="e-detail"><button className="e-back" onClick={()=>setSelected(undefined)}>← 返回地点索引</button><small>地理区域 · 跨年代定位</small><h2>{place.name}在哪儿？</h2><p>{place.description}</p><button className="e-primary" onClick={()=>move([],undefined,place.viewBounds)}>查看地中海南岸全景</button><h3>从这些地点理解北非</h3><div className="h-related">{['carthage','alexandria','lepcis'].map(id=>{const p=ancientPlaces.find(p=>p.id===id);return p?<button key={id} onClick={()=>selectPlace(id)}>{p.name}<span>{p.modern} →</span></button>:null})}</div><a href={place.source} target="_blank" rel="noreferrer">查看区域划分参考 ↗</a></article>:detail?<HistoryDetailCard place={place} detail={detail} places={allPlaces} year={year} onYear={chooseYear} onSelect={selectPlace} onBack={()=>setSelected(undefined)}/>:<article className="e-detail"><button className="e-back" onClick={()=>setSelected(undefined)}>← 返回地点索引</button><small>{place.kind}</small><h2>{context?.title??place.name}</h2><details><summary>其他语言名称</summary><p>{place.aliases[0]}</p></details><dl><dt>对应今天</dt><dd>{place.modern}</dd><dt>代表坐标</dt><dd>{place.coords[1].toFixed(2)}° 北纬 · {Math.abs(place.coords[0]).toFixed(2)}°{place.coords[0]<0?'西经':'东经'}</dd></dl><p>{place.description}</p><h3>{modern?'古今定位':`${yearLabel(year)}的归属`}</h3>{context?<><p>{context.text}</p><a href={context.source} target="_blank" rel="noreferrer">该时点背景资料 ↗</a></>:<p className="e-note">{modern?'古代遗址与现代城市分别定位，不自动视作同一座连续存在的城市。':'该地点在这一年的名称与政治归属尚未核实。定位标记不代表当年已经建城。'}</p>}<h3>居民与语言</h3>{place.id==='naupactus'&&year===-431?<p>修昔底德 2.9 记载居住在此的美塞尼亚人。这是群体居住记载，不是人口比例或精确分布范围。</p>:<p className="e-note">此地此时的族群、语言分布尚未收录。</p>}{!modern&&<HistoryPeriods placeId={place.id} onYear={chooseYear}/>}<a href={place.source} target="_blank" rel="noreferrer">查看地点原始资料 ↗</a></article>):<><p className="e-section-title">{normalized?'搜索结果':'古今地点索引'} · {allPlaces.length} 处已收录</p><p className="e-note">跨年代查找位置。地点存在时间与归属，以详情中的已核实记录为准。</p><div className="e-place-list">{matchingPlaces.map(p=><button key={p.id} onClick={()=>selectPlace(p.id)}><span><strong>{placeLabel(p,year,modern)}</strong><small>{p.modern}</small></span><ArrowRight size={14}/></button>)}</div>{!matchingPlaces.length&&<p>暂无这个地名。可尝试古名、今名或英文名称。</p>}<label className="e-check"><input type="checkbox" checked={pinsOn} onChange={e=>setPinsOn(e.target.checked)}/>显示当前地点标记</label></>}</>}
    {!searchActive&&tab==='events'&&<><p className="e-section-title">沿着路线读历史 · {allBattles.length} 个专题</p><div className="e-event-list">{allBattles.map((b,i)=><button key={b.id} className={battle?.id===b.id?'active':''} onClick={()=>pickBattle(b.id)}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{b.title}</strong><small>{b.period} · {b.stages.length} 个阶段</small></div><ArrowRight size={14}/></button>)}</div><p className="e-note">目前收录古希腊与罗马专题。路线连接史料中的关键地点，表示方向与顺序；未复原连续行军轨迹。</p></>}
    {!searchActive&&tab==='geography'&&<><p className="e-section-title">让地理关系看得见</p><button className="e-tour" onClick={()=>selectPlace("north-africa")}><Globe2 size={18}/><span><strong>北非在哪儿？</strong><small>地中海南岸，从摩洛哥到埃及</small></span><ArrowRight size={14}/></button>{geographyTours.map(t=><button className="e-tour" key={t.id} onClick={()=>{const p=europeLandforms.find(l=>l.id===t.id)!;closeBattle();move([],{center:p.coords,zoom:p.zoom,pitch:threeD?58:0,bearing:p.bearing});setMobilePanel(false)}}><Mountain size={18}/><span><strong>{t.title}</strong><small>{t.text}</small></span><ArrowRight size={14}/></button>)}<p className="e-note">山地高度放大 4 倍，帮助观察起伏。河流、海岸和水深来自现代地理资料。</p><label className="e-check"><input type="checkbox" checked={riversOn} onChange={e=>setRiversOn(e.target.checked)}/>显示现代河流参考</label></>}
    </div><div className="e-sidebar-bottom"><span className="e-live-dot"/> 欧洲史阅读地图 · 首个统一版本 <button onClick={()=>setSourceOpen(true)}>查看覆盖</button></div>
   </aside>
   <section className="g-stage e-stage" aria-label="欧洲地图">
    <GreekMap atlas={atlas} threeD={threeD} modern={false} layer="places" selected={selected} compare={none} command={command} onSelect={selectPlace} onCamera={onCamera} overlay={overlay} selectedArea={selectedArea} onAreaSelect={selectArea} battle={battle} battleStep={step}/>
    <div className="m-view-tools"><button className={threeD?'active':''} aria-label={threeD?'切换俯视地图':'切换3D地形'} aria-pressed={threeD} onClick={()=>setThreeD(v=>!v)}>{threeD?'俯视':'立体'}</button><button title="回到欧洲全景" aria-label="回到欧洲全景" onClick={()=>{closeBattle();setSelected(undefined);setSelectedArea(undefined);setMobilePanel(false);move([])}}><LocateFixed size={21}/></button></div>
    <button className={`m-layers-button ${layersOpen?'active':''}`} onClick={()=>setLayersOpen(v=>!v)} aria-expanded={layersOpen}><span className="m-layer-picture"><Layers size={25}/></span>图层</button>
    {layersOpen&&<section className="m-layers-panel" aria-label="地图图层"><div><h2>地图图层</h2><button aria-label="关闭图层设置" onClick={()=>setLayersOpen(false)}><X size={18}/></button></div><label><input type="checkbox" checked={areasOn} disabled={!!battle} onChange={e=>setAreasOn(e.target.checked)}/><Globe2 size={18}/><span>政权与疆界<small>{battle?'战役路线中暂时隐藏':'按所选年代显示参考区域'}</small></span></label><label><input type="checkbox" checked={riversOn} onChange={e=>setRiversOn(e.target.checked)}/><span>河流<small>现代河道参考</small></span></label><label><input type="checkbox" checked={pinsOn} onChange={e=>setPinsOn(e.target.checked)}/><MapPin size={18}/><span>地点标记<small>历史模式为古代地点参考，不代表当年城市清单</small></span></label>{!modern&&<label><input type="checkbox" checked={references} onChange={e=>setReferences(e.target.checked)}/><span>文化与其他区域<small>与政权区域分别查看</small></span></label>}</section>}
    {!battle&&<div className="e-coverage" role="status"><span className={loading?'is-loading':''}/><div><strong>{loading?'正在读取年代资料…':historyError||geoError||status}</strong>{pinsOn&&!modern&&<small>{activeDetails.length?`当前突出 ${activeDetails.length} 处有时段资料的地点；疆界另按参考快照。`:"地点标记为跨年代定位参考，不代表当年已建城。"}</small>}{!modern&&pinsOn&&year===-431&&<div className="h-alignment-key"><span><i style={{background:"#1673bd"}}/>雅典一方</span><span><i style={{background:"#b94e48"}}/>斯巴达一方</span><span><i style={{background:"#85816b"}}/>中立／未入雅典盟</span><small>点的颜色表示关系，不表示疆界。</small></div>}{!modern&&snapshot&&year!==snapshot.year&&<small>你选择了{yearLabel(year)}；以下采用邻近年代作参考，不代表当年疆界。<button onClick={()=>chooseYear(snapshot.year)}>跳到资料年份 →</button></small>}{!modern&&!snapshot&&<small>现有参考快照范围：前 2000 年—公元 2000 年。可查地名，或切换现代参考。</small>}</div>{(historyError||geoError)&&<button onClick={()=>setRetry(v=>v+1)}>重试</button>}</div>}
    <a className="m-wordmark" href="/" aria-label="欧洲时空地图首页"><Compass size={19}/>欧洲时空地图</a>
    {battle&&currentStage&&<article className="e-story-card" aria-label="战役阶段说明"><button className="e-story-close" aria-label="关闭战役路线" onClick={()=>{closeBattle();move([])}}><X size={17}/></button><span className="e-eyebrow">{currentStage.date} · {step+1} / {battle.stages.length}</span><h3>{currentStage.title}</h3><p>{currentStage.text}</p><div className="e-story-stops">{currentStage.stops.map((s,i)=><span key={`${s.name}-${i}`}><b>{i+1}</b>{s.name}</span>)}</div><details><summary>路线如何理解</summary><p>{battle.caveat}</p></details><a href={currentStage.source} target="_blank" rel="noreferrer">{currentStage.sections} ↗</a></article>}
    {message&&<div className="e-toast" role="status"><Check size={16}/>{message}</div>}
   </section>
  </div>
  <footer className="e-timeline">
   <form onSubmit={e=>{e.preventDefault();const y=parseYear(yearInput);if(y===undefined)setMessage('请输入有效年份，例如“前431”或“1453”。公元纪年没有 0 年。');else chooseYear(y)}}><label htmlFor="atlas-year">前往一个年份</label><div><input id="atlas-year" aria-label="输入历史年份" value={yearInput} onChange={e=>setYearInput(e.target.value)} placeholder="前431 / 1453"/><button type="submit" aria-label="前往输入年份"><ArrowRight size={17}/></button></div></form>
   {battle?<div className="e-route-timeline"><div><strong>{battle.period}</strong><span>按叙事阶段展开，非等速行军</span><button aria-label={playing?'暂停路线播放':'播放路线阶段'} onClick={()=>{if(step===battle.stages.length-1)setStep(0);setPlaying(v=>!v)}}>{playing?<Pause size={15}/>:<Play size={15}/>}</button></div><nav aria-label="战役阶段">{battle.stages.map((s,i)=><button key={s.title} aria-label={`阶段 ${i+1}：${s.title}`} aria-current={step===i?'step':undefined} className={step===i?'active':''} onClick={()=>{setStep(i);setPlaying(false)}}>{i+1}<span>{s.title}</span></button>)}</nav></div>:<div className="e-time-control"><div><strong>{modern?'现代地理参考':yearLabel(year)}</strong><span>{modern?'底图版本 v5.1.1 · 非实时边界':`${boundarySnapshots.length} 个参考年代 · 拖动查看`}</span><select aria-label="选择资料年代" value={modern?'modern':snapshot?.year??''} onChange={e=>e.target.value==='modern'?chooseModern():chooseYear(Number(e.target.value))}><option value="" disabled>暂无对应快照</option>{boundarySnapshots.map(s=><option key={s.year} value={s.year}>{yearLabel(s.year)}</option>)}<option value="modern">现代参考</option></select></div><input type="range" aria-label="历史参考年代时间轴" min="0" max={boundarySnapshots.length-1} value={snapshotIndex} disabled={modern} onChange={e=>chooseYear(boundarySnapshots[Number(e.target.value)].year)}/><div className="e-time-labels"><span>前 2000 年</span><span>参考年代间距不等于时间长度</span><span>公元 2000 年</span></div></div>}
   <div className="e-time-actions">{battle?<><button disabled={step===0} aria-label="上一阶段" onClick={()=>{setStep(v=>v-1);setPlaying(false)}}><ArrowLeft size={17}/></button><button disabled={step===battle.stages.length-1} aria-label="下一阶段" onClick={()=>{setStep(v=>v+1);setPlaying(false)}}><ArrowRight size={17}/></button></>:<button className={modern?'active':''} onClick={modern?()=>chooseYear(year):chooseModern}><Globe2 size={18}/>{modern?'回到历史':'现代对照'}</button>}</div>
  </footer>
  <dialog className="e-source-dialog" ref={dialog} onClose={()=>setSourceOpen(false)}><button className="e-dialog-close" aria-label="关闭资料与覆盖" onClick={()=>setSourceOpen(false)} autoFocus><X size={20}/></button><span className="e-eyebrow">资料与覆盖</span><h2>让地图帮助理解，<br/>也让依据看得见。</h2><p>当前是欧洲时空地图的首个统一版本，已经连通时间、地点、地形和 {allBattles.length} 个战役专题；还没有覆盖全部欧洲史。</p><dl><dt>历史区域</dt><dd>{boundarySnapshots.length} 个候选参考快照，前 2000 年至公元 2000 年。原资料包含政权、文化和其他区域；类别初步整理，边界尚未逐项核实。<a href={HISTORY_SOURCE} target="_blank" rel="noreferrer">Historical Basemaps · GPL-3.0 ↗</a></dd><dt>古今地点</dt><dd>共 {ancientPlaces.length} 处历史地点：原有古希腊、古罗马与青铜时代索引，另补 {coursePlaces.length} 处跨时代地点；逐点列明定位来源。现代城市参考来自 Natural Earth。坐标是定位参考；已补古希腊、罗马晚期、中世纪与近代早期的部分时段说明，其他时期仍有缺口。<a href="https://pleiades.stoa.org/" target="_blank" rel="noreferrer">Pleiades contributors · CC BY 3.0 ↗</a></dd><dt>现代参考</dt><dd>Natural Earth v5.1.1 国家与地区、城市、河流；公有领域。2026-09-10 获取，不代表 2026 年逐日实时政治边界。采用资料原有的区域划分。<a href={MODERN_SOURCE} target="_blank" rel="noreferrer">Natural Earth 原始资料 ↗</a></dd><dt>地形</dt><dd>西经 25°—东经 55°，北纬 24°—72°；1,195 对高程图块。高度 ×4，海底深度仅用于颜色，地形与海岸是现代参考。<a href="https://registry.opendata.aws/terrain-tiles/" target="_blank" rel="noreferrer">Mapzen / AWS Terrain Tiles ↗</a></dd><dt>本次阅读材料</dt><dd>《{courseDocument.title}》共 {courseDocument.pages.toLocaleString()} 页，已建立 {courseDocument.chapters} 讲的目录索引。据课程相关章节累计补充 {courseDetails.length} 条时段记录，详情标明讲次和 PDF 页码；目录提取不等于全部内容已进入地图。</dd><dt>居民与语言</dt><dd>已在部分历史地点详情中分别记录居民身份与书写语言证据；目前没有全欧洲族群或语言的边界与比例分布层。居民身份不能由疆界推导。</dd><dt>Blender 与网站</dt><dd>网站直接生成可查询的立体地图；既有 Blender 场景保留。后续地形与场景资产可从 Blender 导入，时间和疆界以共同数据为准。</dd></dl><p>没有精确年份的数据时，显示邻近参考年代；不生成未经考证的中间疆界。未收录区域不能理解为“无人居住”。</p><div className="e-legacy-links"><a href="?atlas=greece">已有古希腊专题 ↗</a><a href="?atlas=rome">已有古罗马专题 ↗</a></div></dialog>
 </main>;
}
