// @vitest-environment jsdom
import raw300 from '../../public/historical-boundaries/world_300.geojson?raw';
import {afterEach,describe,it,expect,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {EuropeApp} from './EuropeApp';
vi.mock('../greek/GreekMap',()=>({GreekMap:({overlay,onAreaSelect}:{overlay:{areas:GeoJSON.FeatureCollection;lines?:GeoJSON.FeatureCollection;labels:{id:string;name:string}[]};onAreaSelect:(id:string)=>void})=><div><div data-testid="reading-lines">{overlay.lines?.features.map(f=>f.properties?.atlasId).join(',')}</div><div data-testid="drawn-areas">{overlay.areas.features.map(f=>f.properties?.name).join(',')}</div><div data-testid="map-labels">{overlay.labels.map(p=><button key={p.id} aria-label={'地图标签：'+p.name} onClick={()=>onAreaSelect(p.id)}>{p.name}</button>)}</div></div>}));
HTMLDialogElement.prototype.showModal=function(){this.open=true};
HTMLDialogElement.prototype.close=function(){this.open=false};
const empty={type:'FeatureCollection',features:[]};
function fc(name:string){return {type:'FeatureCollection',features:[{type:'Feature',properties:{name,subject:name},geometry:{type:'Polygon',coordinates:[[[10,40],[20,40],[20,50],[10,50],[10,40]]]}}]}}
const response=(data:unknown)=>({ok:true,json:async()=>data}) as Response;
vi.setConfig({testTimeout:15000});
afterEach(()=>{cleanup();vi.unstubAllGlobals();history.replaceState(null,'','/')});
describe('timeline rendering',()=>{
 it('restores a 395 administrative division, follows regions and leaves geometry at another year',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(fc('Western Roman Empire'))));history.replaceState(null,'','/?year=395&view=administration&division=italy');render(<EuropeApp/>);
  const card=screen.getByRole('region',{name:'395 年行政分区'});
  expect(within(card).getByRole('heading',{name:'意大利行政大区'})).toBeTruthy();
  expect(screen.getByTestId('drawn-areas').textContent).toContain('高卢行政大区');
  expect(screen.getByTestId('drawn-areas').textContent).not.toContain('Western Roman Empire');
  fireEvent.click(within(card).getByRole('button',{name:/迦太基与阿非利加.*地域、居民与语言/}));
  expect(location.search).toContain('region=africa');expect(location.search).not.toContain('division=');
  expect(screen.getByRole('article',{name:'395 年地域详情'})).toBeTruthy();
  fireEvent.click(screen.getByRole('button',{name:'返回城市归属对照'}));
  expect(location.search).toContain('view=control');
  expect(screen.getByTestId('drawn-areas').textContent).toBe('');
  fireEvent.click(screen.getByRole('button',{name:'年代'}));
  fireEvent.click(screen.getByRole('button',{name:'打开 395 年行政分区示意 →'}));
  fireEvent.click(within(screen.getByRole('region',{name:'关键年份政权对照'})).getByRole('button',{name:'476 年'}));
  expect(location.search).toContain('year=476');expect(location.search).not.toContain('administration');
  expect(screen.getByTestId('drawn-areas').textContent).toBe('');
  await act(async()=>{});
 });
 it('does not accept an administrative layer dated to 400 or modern geography',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=400&view=administration&division=east');render(<EuropeApp/>);
  expect(screen.getByTestId('drawn-areas').textContent).toBe('');expect(location.search).not.toContain('administration');
  expect(location.search).not.toContain('division');await act(async()=>{});
 });

 it('restores event moments, hides borrowed polygons and keeps Dalmatia separate',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(fc('Western Roman Empire'))));history.replaceState(null,'','/?year=476&view=control&moment=before');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:'年代'}));
  const guide=screen.getByRole('region',{name:'关键年份政权对照'});
  expect(within(guide).getByRole('button',{name:'8—9月更替前'}).getAttribute('aria-pressed')).toBe('true');
  await waitFor(()=>expect(screen.getByTestId('drawn-areas').textContent).toBe(''));
  expect(screen.getByLabelText('地图地点归属图例').textContent).toContain('尼波斯');
  fireEvent.click(within(guide).getByRole('button',{name:'更替后'}));
  expect(location.search).toContain('moment=after');
  expect(screen.getByLabelText('地图地点归属图例').textContent).toContain('奥多亚克');
  fireEvent.click(within(guide).getByRole('button',{name:/拉文纳.*查看城市/}));
  expect(location.search).toContain('place=ravenna');expect(location.search).toContain('view=control');
  expect(screen.getByLabelText('所选地点的事件对照').textContent).toContain('奥多亚克');
  await act(async()=>{});
 });
 it('compares the capture and treaty as different events and explicitly returns to reference geometry',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(fc('Eastern Roman Empire'))));history.replaceState(null,'','/?year=439');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:'年代'}));
  fireEvent.click(within(screen.getByRole('region',{name:'关键年份政权对照'})).getByRole('button',{name:'442 年'}));
  expect(location.search).toContain('year=442');
  expect(screen.getByLabelText('地图地点归属图例').textContent).toContain('汪达尔');
  fireEvent.click(screen.getByRole('button',{name:'查看百年疆界参考'}));
  expect(location.search).toContain('view=reference');expect(location.search).not.toContain('moment=');
  await waitFor(()=>expect(screen.getByTestId('drawn-areas').textContent).toContain('Eastern Roman Empire'));
  expect(screen.getByText(/公元 442 年 · 连续分期资料 \/ 400 年疆界参考/)).toBeTruthy();
  fireEvent.click(screen.getByRole('button',{name:'查看 442 年地点归属对照 →'}));
  expect(location.search).toContain('view=control');
  fireEvent.click(within(screen.getByRole('region',{name:'关键年份政权对照'})).getByRole('button',{name:'493 年'}));
  fireEvent.click(within(screen.getByRole('region',{name:'关键年份政权对照'})).getByRole('button',{name:'拉文纳交接前'}));
  expect(screen.getByLabelText('地图地点归属图例').textContent).toContain('逐城控制待核');
  await act(async()=>{});
 });
 it('opens the Narbonne subregion in the handover year and restores the earlier North African treaty route',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=462&region=gaul');render(<EuropeApp/>);
  const gaul=await screen.findByRole('article',{name:'462 年地域详情'});
  fireEvent.click(within(gaul).getByRole('button',{name:/纳博讷.*展开内部地域/}));
  expect(location.search).toContain('region=narbonensis5');
  const local=screen.getByRole('article',{name:'462 年地域详情'});
  fireEvent.click(within(local).getByRole('button',{name:/纳尔博.*查看地域内或相邻城市/}));
  expect(location.search).toContain('place=narbonne');expect(location.search).toContain('year=462');
  expect(screen.getByText(/本年阿格里皮努斯将纳博讷/)).toBeTruthy();
  await act(async()=>{});
  cleanup();history.replaceState(null,'','/?year=429&battle=vandals-429&stage=2');render(<EuropeApp/>);
  expect(screen.getByRole('article',{name:'战役阶段说明'}).textContent).toContain('435');
  expect(screen.getByRole('article',{name:'战役阶段说明'}).textContent).toContain('迦太基还未易手');
  await act(async()=>{});
 });
 it('moves through the unified centuries overview and reaches newly retained Caucasus regions',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=401');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:'年代'}));
  const overview=await screen.findByRole('region',{name:'4—5世纪地图总览'});
  expect(overview.textContent).toContain('48 组地域');expect(overview.textContent).toContain('74 处');
  fireEvent.change(within(overview).getByLabelText('四至五世纪连续时间轴'),{target:{value:'428'}});
  fireEvent.click(within(screen.getByRole('region',{name:'4—5世纪地图总览'})).getByRole('button',{name:/亚美尼亚与高加索/}));
  expect(location.search).toContain('year=428');expect(location.search).toContain('region=armenia');
  expect(screen.getByRole('article',{name:'428 年地域详情'}).textContent).toContain('总督体制');
  fireEvent.click(screen.getByRole('button',{name:'年代'}));
  fireEvent.click(within(screen.getByRole('region',{name:'4—5世纪地图总览'})).getByRole('button',{name:'四世纪起点 · 301 年'}));
  expect(location.search).toContain('year=301');expect(location.search).not.toContain('region=');
  await act(async()=>{});
 });
 it('opens the fifth-century war from the annual guide and restores a shared route stage',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=451');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:'年代'}));
  const guide=await screen.findByRole('region',{name:'400—500 年连续历史导览'});
  fireEvent.click(within(guide).getByRole('button',{name:/分阶段查看五世纪战役/}));
  expect(location.search).toContain('battle=attila-gaul-451');expect(location.search).toContain('year=451');
  fireEvent.click(screen.getByRole('button',{name:/阶段 3：东高卢会战与撤出/}));
  expect(location.search).toContain('stage=2');expect(screen.getByRole('article',{name:'战役阶段说明'}).textContent).toContain('精确位置有讨论');
  await act(async()=>{});
  cleanup();history.replaceState(null,'','/?year=489&battle=theodoric-489&stage=3');render(<EuropeApp/>);
  expect(screen.getByRole('article',{name:'战役阶段说明'}).textContent).toContain('493年');
  expect(location.search).toContain('stage=3');
  fireEvent.click(screen.getByLabelText('关闭战役路线'));
  expect(location.search).not.toContain('battle=');expect(location.search).toContain('year=489');
  await act(async()=>{});
 });
 it('locates inland Auvergne, its ancient city and the coast separately without losing the year',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=475&region=gaul');render(<EuropeApp/>);
  const gaul=await screen.findByRole('article',{name:'475 年地域详情'});
  fireEvent.click(within(gaul).getByRole('button',{name:/奥弗涅与克莱蒙.*展开内部地域/}));
  expect(location.search).toContain('region=auvergne5');
  expect(screen.getByRole('article',{name:'475 年地域详情'}).textContent).toContain('和议将奥弗涅让给西哥特');
  fireEvent.click(screen.getByRole('button',{name:/阿尔维尔纳.*查看地域内或相邻城市/}));
  expect(location.search).toContain('place=clermont5');expect(location.search).toContain('year=475');
  expect(screen.getAllByText(/罗马时期古名奥古斯托内梅图姆/).length).toBeGreaterThan(0);
  fireEvent.click(screen.getByRole('button',{name:/^阿雷拉特（阿尔勒）/}));
  expect(location.search).toContain('place=arles');
  expect(screen.getByText(/尼波斯在 474—475 年前后短暂恢复/)).toBeTruthy();
  await act(async()=>{});
 });
 it('opens a fifth-century subregion, its city and its parent without losing the year',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=476&region=gaul');render(<EuropeApp/>);
  const region=await screen.findByRole('article',{name:'476 年地域详情'});
  fireEvent.click(within(region).getByRole('button',{name:/普罗旺斯与罗讷河下游.*展开内部地域/}));
  expect(location.search).toContain('region=provence5');
  expect(screen.getByRole('article',{name:'476 年地域详情'}).textContent).toContain('转入西哥特');
  fireEvent.click(within(screen.getByRole('article',{name:'476 年地域详情'})).getByRole('button',{name:/阿尔勒.*查看地域内或相邻城市/}));
  expect(location.search).toContain('place=arles');expect(location.search).toContain('year=476');
  fireEvent.click(screen.getByRole('button',{name:/查看所在地域：普罗旺斯/}));
  fireEvent.click(screen.getByRole('button',{name:'← 返回高卢'}));
  expect(location.search).toContain('region=gaul');expect(location.search).toContain('year=476');
  await act(async()=>{});
 });
 it('moves through the fifth century and keeps Dalmatia separate from Italy after 476',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=475');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:/历史年代/}));
  fireEvent.change(screen.getByLabelText('五世纪逐年时间轴'),{target:{value:'477'}});
  const guide=screen.getByRole('region',{name:'400—500 年连续历史导览'});
  expect(guide.textContent).toContain('尼波斯仍在达尔马提亚');
  fireEvent.click(within(guide).getByRole('button',{name:/展开意大利地域/}));
  expect(location.search).toContain('region=italy');
  expect(screen.getByRole('article',{name:'477 年地域详情'}).textContent).toContain('奥多亚克');
  fireEvent.click(screen.getByRole('button',{name:/罗马.*查看地域内或相邻城市/}));
  expect(location.search).toContain('place=rome');expect(location.search).toContain('year=477');
  fireEvent.click(screen.getByRole('button',{name:/查看所在地域：意大利/}));
  expect(location.search).toContain('region=italy');
  await act(async()=>{});
 });
 it('reads AD 400 from the court guide through a North African region and city',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=400');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:/历史年代/}));
  const guide=screen.getByRole('region',{name:'400 年详细阅读导览'});
  expect(guide.textContent).toContain('伊嗣俟一世');
  fireEvent.click(within(guide).getByText('北非属于谁？为什么对意大利重要？'));
  fireEvent.click(within(guide).getByRole('button',{name:/西侧：的黎波里塔尼亚/}));
  expect(location.search).toContain('region=tripolitania400');
  fireEvent.click(screen.getByRole('button',{name:/大莱普提斯.*查看地域内或相邻城市/}));
  expect(location.search).toContain('place=lepcis');expect(location.search).toContain('year=400');
  fireEvent.click(screen.getByRole('button',{name:/查看所在地域：的黎波里塔尼亚/}));
  expect(location.search).toContain('region=tripolitania400');
  await act(async()=>{});
 });
 it('moves year by year through the treaty and keeps a dated city and region linked',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=362');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:/历史年代/}));
  fireEvent.change(screen.getByLabelText('四世纪逐年时间轴'),{target:{value:'364'}});
  expect(location.search).toContain('year=364');
  const guide=screen.getByRole('region',{name:'300—400 年连续历史导览'});
  fireEvent.click(within(guide).getByRole('button',{name:'尼西比斯：萨珊控制 →'}));
  expect(location.search).toContain('place=nisibis');
  expect(screen.getByText(/萨珊帝国控制，363 年已由罗马交出/)).toBeTruthy();
  fireEvent.click(screen.getByRole('button',{name:/查看所在地域：上美索不达米亚/}));
  expect(location.search).toContain('region=mesopotamia');
  expect(screen.getByRole('article',{name:'364 年地域详情'}).textContent).toContain('埃德萨仍属罗马');
  await act(async()=>{});
 });
 it('opens a century event battle and removes the century layer outside the range',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=363');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:/历史年代/}));
  const guide=screen.getByRole('region',{name:'300—400 年连续历史导览'});
  fireEvent.click(within(guide).getByRole('button',{name:'分阶段查看战役 →'}));
  expect(location.search).toContain('battle=persian-363');
  fireEvent.click(screen.getByRole('button',{name:/阶段 4：和议改变边界/}));
  expect(location.search).toContain('stage=3');
  fireEvent.click(screen.getByRole('button',{name:/历史年代/}));
  fireEvent.change(screen.getByLabelText('四世纪逐年时间轴'),{target:{value:'400'}});
  fireEvent.click(screen.getByRole('button',{name:'500 年'}));
  expect(screen.queryByRole('region',{name:'300—400 年连续历史导览'})).toBeNull();
  expect(screen.queryByRole('button',{name:'地图标签：匈人活动方向'})).toBeNull();
  await act(async()=>{});
 });
 it('navigates from the Sasanian empire through its homeland and city and back',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=300&region=persia');render(<EuropeApp/>);
  expect(screen.getByRole('region',{name:'300 年罗马与萨珊对照'}).textContent).toContain('纳尔塞');
  fireEvent.click(screen.getByRole('button',{name:/帕尔斯.*展开帝国内部地域/}));
  expect(location.search).toContain('region=pars');
  fireEvent.click(screen.getByRole('button',{name:/比沙普尔.*查看核心地点/}));
  expect(location.search).toContain('place=bishapur');expect(location.search).not.toContain('region=');
  fireEvent.click(screen.getByRole('button',{name:/查看所在地域：帕尔斯/}));
  fireEvent.click(screen.getByRole('button',{name:'← 返回萨珊帝国'}));
  expect(location.search).toContain('region=persia');
  fireEvent.click(screen.getByRole('button',{name:/罗马对手：伽列里乌斯/}));
  expect(location.search).toContain('ruler=galerius');expect(location.search).not.toContain('region=');
  await act(async()=>{});
 });
 it('finds Narseh in the Sasanian profile and hides its regional details in other years',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=300');render(<EuropeApp/>);
  fireEvent.focus(screen.getByLabelText('搜索地点、政权或战役'));
  fireEvent.change(screen.getByLabelText('搜索地点、政权或战役'),{target:{value:'纳尔塞'}});fireEvent.submit(screen.getByRole('search'));
  expect(location.search).toContain('region=persia');
  fireEvent.click(screen.getByRole('button',{name:/返回 300 年地域索引/}));
  fireEvent.click(screen.getByRole('button',{name:'400 年'}));
  expect(location.search).not.toContain('region=');
  expect(screen.queryByRole('region',{name:'300 年罗马与萨珊对照'})).toBeNull();
  expect(screen.getByRole('button',{name:'地图标签：帕尔斯（法尔斯）'})).toBeTruthy();
  await act(async()=>{});
 });
 it('opens all four ruler cards from the actual political map labels',async()=>{
  vi.stubGlobal('fetch',vi.fn(async(url)=>response(String(url).includes('world_300')?JSON.parse(raw300):empty)));
  history.replaceState(null,'','/?year=300');render(<EuropeApp/>);
  const rulers=[['西北','君士坦提乌斯一世','constantius'],['西部','马克西米安','maximian'],['巴尔干','伽列里乌斯','galerius'],['东方','戴克里先','diocletian']];
  for(const [direction,name,id] of rulers){
   const label=await screen.findByRole('button',{name:'地图标签：罗马帝国 · '+direction+'分掌区'},{timeout:10000});
   fireEvent.click(label);
   expect(screen.getByRole('article',{name:'300 年皇帝与分掌区'}).textContent).toContain(name);
   expect(location.search).toContain('ruler='+id);
  }
  await act(async()=>{});
 });
 it('restores a ruler share URL and navigates to its partner, region and frontier',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=300&ruler=constantius');render(<EuropeApp/>);
  expect(screen.getByRole('article',{name:'300 年皇帝与分掌区'}).textContent).toContain('正帝：305—306 年');
  fireEvent.click(screen.getByRole('button',{name:/同组共治者：马克西米安/}));expect(location.search).toContain('ruler=maximian');
  fireEvent.click(screen.getByRole('button',{name:/意大利半岛.*组成地域、居民与语言/}));
  expect(location.search).toContain('region=italy');expect(location.search).not.toContain('ruler=');
  fireEvent.click(screen.getByRole('button',{name:/西方正帝.*马克西米安/}));
  fireEvent.click(screen.getByRole('button',{name:/下莱茵河边防.*查看防线与邻国/}));
  expect(location.search).toContain('frontier=lower-rhine');expect(location.search).not.toContain('ruler=');
  await act(async()=>{});
 });
 it('finds a ruler by name and removes its selection on year changes',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=300');render(<EuropeApp/>);
  fireEvent.focus(screen.getByLabelText('搜索地点、政权或战役'));
  fireEvent.change(screen.getByLabelText('搜索地点、政权或战役'),{target:{value:'戴克里先'}});fireEvent.submit(screen.getByRole('search'));
  expect(location.search).toContain('ruler=diocletian');
  fireEvent.click(screen.getByRole('button',{name:/尼科米底亚.*重要宫廷驻地/}));
  expect(location.search).toContain('place=nicomedia');expect(location.search).not.toContain('ruler=');
  fireEvent.click(screen.getByRole('button',{name:/历史年代/}));fireEvent.click(screen.getByRole('button',{name:'400 年'}));
  expect(screen.queryByRole('region',{name:'300 年皇帝入口'})).toBeNull();expect(location.search).not.toContain('ruler=');
  await act(async()=>{});
 });

 it('opens border labels, then regions and cities without retaining incompatible selection URLs',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=300');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:'地图标签：下莱茵河边防'}));
  expect(location.search).toContain('frontier=lower-rhine');
  expect(screen.getByRole('article',{name:'300 年边防详情'}).textContent).toContain('特里尔在更南的摩泽尔河');
  fireEvent.click(screen.getByRole('button',{name:/高卢.*地域组成与语言/}));
  expect(location.search).toContain('region=gaul');expect(location.search).not.toContain('frontier=');
  fireEvent.click(screen.getByRole('button',{name:/下莱茵河边防.*边防走廊/}));
  fireEvent.click(screen.getByRole('button',{name:/科隆.*查看城市与居民/}));
  expect(location.search).toContain('place=cologne');expect(location.search).not.toContain('frontier=');expect(location.search).not.toContain('region=');
  await act(async()=>{});
 });
 it('restores frontier links and hides every frontier line on year or modern-mode changes',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=300&frontier=eastern-contact');render(<EuropeApp/>);
  expect(screen.getByRole('article',{name:'300 年边防详情'}).textContent).toContain('不是国界');
  expect(screen.getByTestId('reading-lines').textContent).toContain('frontier300:hadrian');
  fireEvent.click(screen.getByRole('button',{name:/现代对照/}));
  expect(screen.getByTestId('reading-lines').textContent).toBe('');expect(location.search).not.toContain('frontier=');
  await act(async()=>{});
 });
 it('searches the frontier independently and supports its separate layer switch',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=300');render(<EuropeApp/>);
  fireEvent.focus(screen.getByLabelText('搜索地点、政权或战役'));
  fireEvent.change(screen.getByLabelText('搜索地点、政权或战役'),{target:{value:'哈德良长城'}});
  fireEvent.submit(screen.getByRole('search'));
  expect(location.search).toContain('frontier=hadrian');
  fireEvent.click(screen.getByRole('button',{name:'图层'}));
  fireEvent.click(screen.getByRole('checkbox',{name:/300 年边防与东方关系/}));
  expect(screen.getByTestId('reading-lines').textContent).toBe('');
  expect(screen.queryByRole('button',{name:'地图标签：哈德良长城'})).toBeNull();
  fireEvent.click(screen.getByRole('button',{name:'查看整段范围 →'}));
  expect(screen.getByTestId('reading-lines').textContent).toContain('frontier300:hadrian');
  fireEvent.click(screen.getByRole('button',{name:/返回 300 年地域索引/}));
  fireEvent.click(screen.getByRole('button',{name:'400 年'}));
  expect(screen.getByTestId('reading-lines').textContent).toBe('');expect(location.search).not.toContain('frontier=');
  await act(async()=>{});
 });

 it('opens a geographic label, a local city, and returns to the same 300 region',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=300');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:'地图标签：潘诺尼亚与达尔马提亚'}));
  expect(location.search).toContain('region=pannonia');expect(screen.getByRole('article',{name:'300 年地域详情'}).textContent).toContain('萨瓦河');
  fireEvent.click(screen.getByRole('button',{name:/西尔米乌姆.*查看地域内或相邻城市/}));
  expect(location.search).toContain('place=sirmium');expect(location.search).not.toContain('region=');
  fireEvent.click(screen.getByRole('button',{name:/查看所在地域：潘诺尼亚与达尔马提亚/}));
  expect(location.search).toContain('region=pannonia');expect(location.search).not.toContain('place=');
  await act(async()=>{});
 });
 it('restores a shared region and removes its labels and URL when changing years',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=300&region=armenia');render(<EuropeApp/>);
  expect(screen.getByRole('article',{name:'300 年地域详情'}).textContent).toContain('阿尔沙克');
  fireEvent.click(screen.getByRole('button',{name:/返回 300 年地域索引/}));
  fireEvent.click(screen.getByRole('button',{name:'400 年'}));
  expect(location.search).not.toContain('region=');expect(screen.getByRole('button',{name:'地图标签：亚美尼亚王国'})).toBeTruthy();
  await act(async()=>{});
 });
 it('finds historical regions in search and toggles their map labels',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=300');render(<EuropeApp/>);
  fireEvent.focus(screen.getByLabelText('搜索地点、政权或战役'));
  fireEvent.change(screen.getByLabelText('搜索地点、政权或战役'),{target:{value:'高加索伊比利亚'}});
  fireEvent.submit(screen.getByRole('search'));
  expect(location.search).toContain('region=iberia-caucasus');
  fireEvent.click(screen.getByRole('button',{name:'图层'}));
  fireEvent.click(screen.getByRole('checkbox',{name:/300—500 年地域标签/}));
  expect(screen.queryByRole('button',{name:'地图标签：高加索伊比利亚'})).toBeNull();
  await act(async()=>{});
 });
 it('renders the real 300 Roman divisions without enabling reference areas and opens the eastern neighbor',async()=>{
  vi.stubGlobal('fetch',vi.fn(async(url)=>response(String(url).includes('world_300')?JSON.parse(raw300):empty)));
  history.replaceState(null,'','/?year=300');render(<EuropeApp/>);
  await waitFor(()=>expect(screen.getByTestId('drawn-areas').textContent).toContain('Rome (Diocletianus)'));
  expect(screen.getByTestId('drawn-areas').textContent).toContain('Rome (Constantinus)');
  expect(screen.getByTestId('drawn-areas').textContent).not.toContain('Parthian Empire');
  fireEvent.click(screen.getByRole('button',{name:/历史年代/}));
  expect(screen.getByRole('region',{name:'政权与地域组成'}).textContent).toContain('北非沿海');
  fireEvent.click(screen.getByRole('button',{name:/萨珊宫廷：泰西封/}));
  expect(location.search).toContain('year=300');expect(location.search).toContain('place=ctesiphon');
  expect(screen.getByText(/不能仍把 300 年的波斯称为帕提亚帝国/)).toBeTruthy();
 });
 it('opens the Norman century and locates Sicily without creating an early kingdom',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=1066');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:/历史年代/}));
  fireEvent.click(screen.getByRole('button',{name:'1100 年'}));
  expect(screen.getByRole('region',{name:'政权与地域组成'}).textContent).toContain('不同君主');
  fireEvent.click(screen.getByRole('button',{name:/岛屿一侧：巴勒莫/}));
  expect(location.search).toContain('year=1100');expect(location.search).toContain('place=palermo');
  expect(screen.getByText(/西西里王国到 1130 年才成立/)).toBeTruthy();
  expect(screen.getByText('第 164 讲 · PDF 第 1391—1396 页')).toBeTruthy();
  await act(async()=>{});
 });
 it('finds the Norman route and moves from a later year to its dated stages',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=1100');render(<EuropeApp/>);
  fireEvent.focus(screen.getByLabelText('搜索地点、政权或战役'));
  fireEvent.change(screen.getByLabelText('搜索地点、政权或战役'),{target:{value:'诺曼征服'}});
  fireEvent.click(screen.getByRole('button',{name:/诺曼征服与黑斯廷斯战役/}));
  expect(location.search).toContain('year=1066');
  fireEvent.click(screen.getByRole('button',{name:'阶段 3：战役之后：伦敦加冕'}));
  expect(screen.getByRole('button',{name:'阶段 3：战役之后：伦敦加冕'}).getAttribute('aria-current')).toBe('step');
  expect(screen.getByText(/不能拿来判断实际进军道路/)).toBeTruthy();
  await act(async()=>{});
 });
 it('opens the millennium realm comparison and its Polish checkpoint with course references',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=962');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:/历史年代/}));
  fireEvent.click(screen.getByRole('button',{name:'1000 年'}));
  expect(screen.getByRole('region',{name:'政权与地域组成'}).textContent).toContain('法兰西王国与王室领地');
  fireEvent.click(screen.getByRole('button',{name:/查看会晤与王号/}));
  expect(location.search).toContain('year=1000');expect(location.search).toContain('place=gniezno');
  expect(screen.getByText(/1025 年正式加冕为波兰国王是两个节点/)).toBeTruthy();
  expect(screen.getByText('第 155 讲 · PDF 第 1304—1306 页')).toBeTruthy();
  await act(async()=>{});
 });
 it('navigates the partition guide and keeps the selected year when opening its regions',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=800');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:/历史年代/}));
  fireEvent.click(screen.getByRole('button',{name:'843 年'}));
  expect(screen.getByRole('region',{name:'政权与地域组成'}).textContent).toContain('中部王国 · 洛泰尔一世');
  fireEvent.click(screen.getByRole('button',{name:/南段：帕维亚/}));
  expect(location.search).toContain('year=843');expect(location.search).toContain('place=pavia');
  expect(screen.getByText(/它与亚琛同在中部体系/)).toBeTruthy();
  expect(screen.getByText('第 144 讲 · PDF 第 1209—1211 页')).toBeTruthy();
  await act(async()=>{});
 });
 it('switches from 600 to 700 and opens the Umayyad capital with course references',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=600');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:/历史年代/}));
  fireEvent.click(screen.getByRole('button',{name:'700 年'}));
  expect(location.search).toContain('year=700');
  fireEvent.click(screen.getByRole('button',{name:/倭马亚都城 → 大马士革/}));
  expect(location.search).toContain('place=damascus');
  expect(screen.getByText('第 150 讲 · PDF 第 1256—1263 页')).toBeTruthy();
  expect(screen.getByText(/此时还不能使用后来阿拔斯时代的巴格达/)).toBeTruthy();
  await act(async()=>{});
 });
 it('opens a late antique kingdom from the year guide and retains its year',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=500');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:/历史年代/}));
  fireEvent.click(screen.getByRole('button',{name:/汪达尔 → 迦太基/}));
  expect(location.search).toContain('year=500');expect(location.search).toContain('place=carthage');
  expect(screen.getByText(/500 年这里已经不受西罗马/)).toBeTruthy();
  expect(screen.getByText('第 133 讲 · PDF 第 1125—1129 页')).toBeTruthy();
  await act(async()=>{});
 });
 it('opens Byzantium by search, retains the topic through 1204 and 1261, and removes obsolete empire boundaries after 1453',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(fc('Byzantine Empire'))));render(<EuropeApp/>);
  fireEvent.focus(screen.getByLabelText('搜索地点、政权或战役'));
  fireEvent.change(screen.getByLabelText('搜索地点、政权或战役'),{target:{value:'拜占庭'}});
  fireEvent.submit(screen.getByRole('search'));
  expect(location.search).toContain('empire=eastern-rome');
  fireEvent.click(screen.getByRole('button',{name:/1204 年.*首都陷落/}));
  expect(screen.getByRole('heading',{name:'首都失陷与多个继承政权'})).toBeTruthy();
  fireEvent.click(screen.getByRole('button',{name:/1261 年.*复都/}));
  await waitFor(()=>expect(screen.getByTestId('drawn-areas').textContent).toBe('Byzantine Empire'));
  fireEvent.click(screen.getByRole('button',{name:/1453 年.*君士坦丁堡陷落/}));
  await waitFor(()=>expect(screen.getByTestId('drawn-areas').textContent).toBe(''));
  fireEvent.click(screen.getByRole('button',{name:/埃及与尼罗河谷.*今天埃及/}));
  expect(screen.getByRole('region',{name:'历史地区说明'}).textContent).toContain('七世纪阿拉伯征服后脱离东罗马');
  fireEvent.click(screen.getByRole('button',{name:/亚历山大.*查看城市/}));
  expect(location.search).toContain('place=alexandria');
  await act(async()=>{});
 });

 it('keeps historical regions available after the western empire ends and opens their cities',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(fc('Western Roman Empire'))));history.replaceState(null,'','/?year=400&empire=western-rome');render(<EuropeApp/>);
  await waitFor(()=>expect(screen.getByTestId('drawn-areas').textContent).toBe('Western Roman Empire'));
  fireEvent.click(screen.getByRole('button',{name:/500 年.*帝国结束/}));
  await waitFor(()=>expect(screen.getByTestId('drawn-areas').textContent).toBe(''));
  expect(location.search).toContain('empire=western-rome');
  fireEvent.click(screen.getByRole('button',{name:/意大利.*今天意大利/}));
  expect(screen.getByRole('region',{name:'历史地区说明'}).textContent).toContain('493 年');
  fireEvent.click(screen.getByRole('button',{name:/拉文纳.*查看城市/}));
  expect(location.search).toContain('place=ravenna');expect(location.search).not.toContain('empire=');
  await act(async()=>{});
 });

 it('navigates course periods with page references and offers known periods outside coverage',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=1204&place=byzantium');render(<EuropeApp/>);
  await waitFor(()=>expect(screen.getByText(/按 1204 年十字军攻陷之后记录/)).toBeTruthy());
  expect(screen.getByText('第 165 讲 · PDF 第 1409—1410 页')).toBeTruthy();
  fireEvent.click(screen.getByRole('button',{name:/东罗马复都：1261—1452 年/}));
  expect(screen.getByText(/1261 年恢复东罗马统治/)).toBeTruthy();expect(location.search).toContain('year=1261');
  fireEvent.change(screen.getByLabelText('输入历史年份'),{target:{value:'1454'}});fireEvent.click(screen.getByLabelText('前往输入年份'));
  expect(screen.getByText(/该地点在这一年的名称与政治归属尚未核实/)).toBeTruthy();
  fireEvent.click(screen.getByRole('button',{name:/新罗马：330—394 年/}));
  expect(screen.getByText(/330 年新都落成后的罗马帝国政治中心/)).toBeTruthy();expect(location.search).toContain('year=330');
  await act(async()=>{});
 });
 it('changes the selected site evidence when the year changes and does not extrapolate it',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=-1500&place=knossos');render(<EuropeApp/>);
  await waitFor(()=>expect(screen.getByText(/线形文字 A 用于这一时期/)).toBeTruthy());
  fireEvent.change(screen.getByLabelText('输入历史年份'),{target:{value:'-1350'}});fireEvent.click(screen.getByLabelText('前往输入年份'));
  expect(screen.getByText(/线形文字 B 记录早期希腊语/)).toBeTruthy();
  expect(screen.queryByText(/线形文字 A 用于这一时期/)).toBeNull();
  fireEvent.change(screen.getByLabelText('输入历史年份'),{target:{value:'100'}});fireEvent.click(screen.getByLabelText('前往输入年份'));
  expect(screen.queryByText(/线形文字 B 记录早期希腊语/)).toBeNull();
  expect(screen.getByText(/该地点在这一年的名称与政治归属尚未核实/)).toBeTruthy();
  await act(async()=>{});
 });
 it('drops stale boundaries when an older request finishes after a newer request',async()=>{
  let completeOld!:(r:Response)=>void;
  vi.stubGlobal('fetch',vi.fn((url:string)=>url.endsWith('world_100.geojson')?new Promise<Response>(resolve=>{completeOld=resolve}):Promise.resolve(response(url.endsWith('world_400.geojson')?fc('Eastern Roman Empire'):empty))));
  render(<EuropeApp/>);
  fireEvent.change(screen.getByLabelText('输入历史年份'),{target:{value:'400'}});fireEvent.click(screen.getByLabelText('前往输入年份'));
  await waitFor(()=>expect(screen.getByTestId('drawn-areas').textContent).toBe('Eastern Roman Empire'));
  await act(async()=>completeOld(response(fc('Roman Empire'))));
  expect(screen.getByTestId('drawn-areas').textContent).toBe('Eastern Roman Empire');
  expect(location.search).toBe('?year=400');
 });
 it('keeps the requested year separate from the available evidence year',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=117');render(<EuropeApp/>);
  await waitFor(()=>expect(screen.getByText(/你选择了公元 117 年/)).toBeTruthy());
  await waitFor(()=>expect(screen.getByText(/公元 100 年资料/)).toBeTruthy());
  fireEvent.change(screen.getByLabelText('输入历史年份'),{target:{value:'2026'}});fireEvent.click(screen.getByLabelText('前往输入年份'));
  await waitFor(()=>expect(screen.getByText('这个年份的疆界尚未收录')).toBeTruthy());
  expect(screen.getByTestId('drawn-areas').textContent).toBe('');
 });
 it('navigates from a vacant western throne to dated Vandal kings without losing the selected year',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));history.replaceState(null,'','/?year=466');render(<EuropeApp/>);
  fireEvent.click(screen.getByRole('button',{name:/历史年代/}));
  const guide=screen.getByRole('region',{name:'400—500 年连续历史导览'});
  expect(guide.textContent).toContain('西部皇位空缺（465—467）');
  expect(within(guide).getByText('北非：迦太基与汪达尔')).toBeTruthy();
  fireEvent.change(screen.getByLabelText('五世纪逐年时间轴'),{target:{value:'484'}});
  expect(location.search).toContain('year=484');
  fireEvent.click(within(guide).getByRole('button',{name:'查看迦太基 →'}));
  expect(location.search).toContain('place=carthage');
  expect(screen.getByText(/胡内里克去世，贡塔蒙德继位/)).toBeTruthy();
  fireEvent.click(screen.getByRole('button',{name:/查看所在地域：迦太基与阿非利加核心区/}));
  expect(location.search).toContain('region=carthage-region5');
  expect(screen.getByRole('article',{name:'484 年地域详情'}).textContent).toContain('贡塔蒙德');
  await act(async()=>{});
 });
 it('rejects invalid year zero without silently changing the displayed time',async()=>{
  vi.stubGlobal('fetch',vi.fn(async()=>response(empty)));render(<EuropeApp/>);
  fireEvent.change(screen.getByLabelText('输入历史年份'),{target:{value:'0'}});fireEvent.click(screen.getByLabelText('前往输入年份'));
  expect(screen.getByText(/公元纪年没有 0 年/)).toBeTruthy();expect(location.search).toBe('?year=100');
  await act(async()=>{});
 });
});
