export const fifthSources={
 braga5:{title:'UNESCO 申遗材料：布拉加城市沿革',url:'https://whc.unesco.org/document/166333'},
 orleans5:{title:'奥尔良市：古代城市与 451 年事件',url:'https://www.orleans-metropole.fr/fileadmin/orleans/MEDIA/kiosque/ville_art_histoire/vdh_aufildelaville.pdf'},
 chalcedon5:{title:'大都会博物馆：迦克墩会议与东方基督教传统',url:'https://www.metmuseum.org/exhibitions/listings/2012/byzantium-and-islam'},
 burgundy5:{title:'剑桥欧洲史研究：勃艮第安置与罗马西部后继政权',url:'https://www.cambridge.org/core/books/roman-west-ad-200500/breakdown-and-barbarians/C255258C7A4A9366BB181C0CCCD332E5'},
 west5:{title:'罗马皇帝学术百科：瓦伦提尼安三世与西部地域变化',url:'https://roman-emperors.sites.luc.edu/valenIII.htm'},
 endWest5:{title:'罗马皇帝学术百科：罗慕路斯与 476 年（含古代史料）',url:'https://roman-emperors.sites.luc.edu/auggiero.htm'},
 theo5:{title:'罗马皇帝学术百科：狄奥多西二世',url:'https://roman-emperors.sites.luc.edu/theo2.htm'},
 leo5:{title:'罗马皇帝学术百科：利奥一世',url:'https://roman-emperors.sites.luc.edu/leo1.htm'},
 zeno5:{title:'罗马皇帝学术百科：芝诺与巴尔干、意大利',url:'https://roman-emperors.sites.luc.edu/zeno.htm'},
 gaul5:{title:'大都会博物馆：西欧、中欧 1—500 年',url:'https://www.metmuseum.org/toah/ht/05/euw.html'},
 iberia5:{title:'大都会博物馆：伊比利亚半岛 1—500 年',url:'https://www.metmuseum.org/toah/ht/05/eusi.html'},
 britain5:{title:'英格兰遗产：约 410 年以后的人口与政权变化',url:'https://www.english-heritage.org.uk/learn/story-of-england/early-medieval/introduction/'},
 gregory5:{title:'都尔的格雷戈里《法兰克人史》（较晚叙事，年代须辨别）',url:'https://sourcebooks.web.fordham.edu/basis/gregory-hist.asp'},
 jordanesEnd5:{title:'约尔达尼斯《哥特史》末篇：匈人联盟解体与狄奥多里克',url:'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Jordanes/Getica/D*.html'},
 jordanes5:{title:'约尔达尼斯《哥特史》：阿提拉战争与后继集团',url:'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Jordanes/Getica/C*.html'},
 procopius5:{title:'普罗柯比《战争史》：汪达尔战争的五世纪背景',url:'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Procopius/Wars/3B*.html'},
 kawad5:{title:'伊朗百科全书：卡瓦德一世的两次统治',url:'https://www.iranicaonline.org/articles/kawad-i/kawad-i-reign/'},
};
