export const fifthSources={
 vandalTreaty5:{title:'罗兰·施泰纳赫研究：盖萨里克王权、435年和约及教会社群',url:'https://doi.org/10.1515/9783110643503-010'},
 metzLate:{title:'梅斯市：河流位置、罗马旧城与451年战争',url:'https://metz.fr/decouvrir-partager/histoire.php'},
 metzNamesLate:{title:'梅斯市城市研究：Divodurum、Mettis与河流交会',url:'https://metz.fr/fichiers/2017/07/18/20170706_Rapport_de_presentation.pdf'},
 narbonneLate:{title:'Narbo Via博物馆：纳尔博·马尔提乌斯至462年西哥特统治',url:'https://narbovia.fr/accueil-2-2/les-parcours-permanents/parcours-permanent-du-musee/'},
 narbonneChronology:{title:'Narbo Via博物馆教育资料：414年婚姻与462年政治变化',url:'https://narbovia.fr/app/uploads/2022/09/NV_DossierPeda_enseignants.pdf'},
 veronaLate:{title:'UNESCO：维罗纳、阿迪杰河与古代城市遗存',url:'https://whc.unesco.org/en/list/797/'},
 reimsNamesLate:{title:'兰斯市遗产导览：杜罗科尔托鲁姆与罗马高卢城市',url:'https://visitespatrimoines.reims.fr/visite/1'},
 clovisBaptismLate:{title:'研究论文：克洛维受洗与罗马文化，含纪年讨论',url:'https://www.persee.fr/doc/bude_0004-5527_1996_num_1_1_4304'},
 noricum5:{title:'欧吉皮乌斯《圣塞维里努斯传》：多瑙河城市与迁居（圣徒传立场须辨别）',url:'https://ccel.org/ccel/pearse/morefathers/files/severinus_02_text.htm'},
 armeniaReligion5:{title:'伊朗百科全书：萨珊时期基督教与亚美尼亚的 451／484 年变化',url:'https://www.iranicaonline.org/articles/christianity-i/'},
 armeniaWar5:{title:'伊朗百科全书：米赫尔—纳尔塞与 451 年亚美尼亚战争',url:'https://www.iranicaonline.org/articles/mehr-narseh/'},
 georgia5:{title:'伊朗百科全书：格鲁吉亚与伊朗的文学及宗教联系',url:'https://www.iranicaonline.org/articles/georgia-iv-1/'},
 northEurope5:{title:'大都会博物馆：东欧与斯堪的纳维亚 1—500 年',url:'https://www.metmuseum.org/toah/ht/05/eue.html'},
 scotland5:{title:'苏格兰国家博物馆：早期中世纪的地方社会',url:'https://www.nms.ac.uk/collections/departments/scottish-history-archaeology/projects/early-medieval-scotland'},
 ireland5:{title:'爱尔兰国家博物馆：早期中世纪与欧甘文字',url:'https://www.museum.ie/getmedia/52e10d5c-ac70-46f2-bb6b-1dd4c5d28121/Ogham-Code.pdf'},
 westernKings5:{title:'剑桥研究《晚期古代西方的使节与政治交流》：西哥特、苏维汇年表（部分纪年有差异）',url:'https://assets.cambridge.org/97805218/13495/frontmatter/9780521813495_frontmatter.pdf'},
 hydatiusStudy5:{title:'塞格德大学：希达提乌斯《编年史》译注与人物年代',url:'https://acta.bibl.u-szeged.hu/10944/1/doc_068_015-109.pdf'},
 clermont5:{title:'克莱蒙费朗市：奥弗涅围城与 475 年和议',url:'https://clermont-ferrand.fr/sites/default/files/mep_parcours_patrimoinev2_20182019.pdf'},
 clermontNames5:{title:'克莱蒙费朗市：奥古斯托内梅图姆、阿尔维尔纳与今名沿革',url:'https://clermont-ferrand.fr/docs/delib/CM27092022/CM27092022_042_A1.pdf'},
 sidonius5:{title:'西多尼乌斯《书信》：奥弗涅地方精英看和议（当事人立场须辨别）',url:'https://www.earlychristianwritings.com/fathers/sidonius_letters_07book7.html'},
 avitus5:{title:'罗马皇帝学术百科：阿维图斯（455—456）与西部皇位危机',url:'https://roman-emperors.sites.luc.edu/avitus.htm'},
 severus5:{title:'罗马皇帝学术百科：利比乌斯·塞维鲁斯及 465—467 年皇位空缺',url:'https://roman-emperors.sites.luc.edu/libius.htm'},
 anthemius5:{title:'罗马皇帝学术百科：安特米乌斯与 472 年内战',url:'https://roman-emperors.sites.luc.edu/anthemiu.htm'},
 olybrius5:{title:'罗马皇帝学术百科：奥利布里乌斯与 472 年争位',url:'https://roman-emperors.sites.luc.edu/olybrius.htm'},
 glycerius5:{title:'罗马皇帝学术百科：格利凯里乌斯与尼波斯交接（473—474）',url:'https://roman-emperors.sites.luc.edu/glyceriu.htm'},
 vandalKings5:{title:'剑桥研究《晚期古代西方的使节与政治交流》：汪达尔国王年表',url:'https://assets.cambridge.org/97805218/13495/frontmatter/9780521813495_frontmatter.pdf'},
 vandalSociety5:{title:'普罗柯比《战争史》卷一第八章：北非国王与地方势力（较晚叙事须辨别）',url:'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Procopius/Wars/3C*.html'},
 hydatius5:{title:'希达提乌斯《编年史》：五世纪伊比利亚（拉丁文史料，叙事立场须辨别）',url:'https://thelatinlibrary.com/hydatiuschronicon.html'},
 provence5:{title:'剑桥：南高卢 400—550 年的政治与地方社会',url:'https://www.cambridge.org/core/books/popular-culture-and-the-end-of-antiquity-in-southern-gaul-c-400550/introduction/031A53154BB0756296A1A2D4574EED03'},
 tarraco5:{title:'塔拉戈纳市：约 472 年进入西哥特统治与城市延续',url:'https://tgnblog.tarragona.cat/tarraco-capital-visigoda/7693'},
 majorian5:{title:'罗马皇帝学术百科：马约里安的高卢与伊比利亚行动',url:'https://roman-emperors.sites.luc.edu/major.htm'},
 braga5:{title:'UNESCO 申遗材料：布拉加城市沿革',url:'https://whc.unesco.org/document/166333'},
 orleans5:{title:'奥尔良市：古代城市与 451 年事件',url:'https://www.orleans-metropole.fr/fileadmin/orleans/MEDIA/kiosque/ville_art_histoire/vdh_aufildelaville.pdf'},
 chalcedon5:{title:'大都会博物馆：迦克墩会议与东方基督教传统',url:'https://www.metmuseum.org/exhibitions/listings/2012/byzantium-and-islam'},
 burgundy5:{title:'剑桥欧洲史研究：勃艮第安置与罗马西部后继政权',url:'https://www.cambridge.org/core/books/roman-west-ad-200500/breakdown-and-barbarians/C255258C7A4A9366BB181C0CCCD332E5'},
 west5:{title:'罗马皇帝学术百科：瓦伦提尼安三世与西部地域变化',url:'https://roman-emperors.sites.luc.edu/valenIII.htm'},
 endWest5:{title:'罗马皇帝学术百科：罗慕路斯与 476 年（含古代史料）',url:'https://roman-emperors.sites.luc.edu/auggiero.htm'},
 theo5:{title:'罗马皇帝学术百科：狄奥多西二世',url:'https://roman-emperors.sites.luc.edu/theo2.htm'},
 leo5:{title:'罗马皇帝学术百科：利奥一世',url:'https://roman-emperors.sites.luc.edu/leo1.htm'},
 zeno5:{title:'罗马皇帝学术百科：芝诺与巴尔干、意大利',url:'https://roman-emperors.sites.luc.edu/zeno.htm'},
 gaul5:{title:'大都会博物馆：西欧、中欧 1—500 年',url:'https://www.metmuseum.org/toah/ht/05/euw.html'},
 iberia5:{title:'大都会博物馆：伊比利亚半岛 1—500 年',url:'https://www.metmuseum.org/toah/ht/05/eusi.html'},
 britain5:{title:'英格兰遗产：约 410 年以后的人口与政权变化',url:'https://www.english-heritage.org.uk/learn/story-of-england/early-medieval/introduction/'},
 gregory5:{title:'都尔的格雷戈里《法兰克人史》（较晚叙事，年代须辨别）',url:'https://sourcebooks.web.fordham.edu/basis/gregory-hist.asp'},
 jordanesEnd5:{title:'约尔达尼斯《哥特史》末篇：匈人联盟解体与狄奥多里克',url:'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Jordanes/Getica/D*.html'},
 jordanes5:{title:'约尔达尼斯《哥特史》：阿提拉战争与后继集团',url:'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Jordanes/Getica/C*.html'},
 procopius5:{title:'普罗柯比《战争史》：汪达尔战争的五世纪背景',url:'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Procopius/Wars/3B*.html'},
 kawad5:{title:'伊朗百科全书：卡瓦德一世的两次统治',url:'https://www.iranicaonline.org/articles/kawad-i/kawad-i-reign/'},
};
