export const fourthCenturySources={
 ammianus26:{title:'阿米阿努斯《历史》卷二十六：365—366年普罗科皮乌斯争位',url:'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Ammian/26*.html'},
 ammianus27:{title:'阿米阿努斯《历史》卷二十七：不列颠恢复与东方军政',url:'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Ammian/27*.html'},
 ammianus17:{title:'阿米阿努斯《历史》卷十七：莱茵河边防与尤利安',url:'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Ammian/17*.html'},
 arles4:{title:'UNESCO：阿尔勒的罗马遗存与晚期古代城市',url:'https://whc.unesco.org/en/list/164/'},
 paris4:{title:'法国文化部：古代巴黎与塞纳河',url:'https://archeologie.culture.gouv.fr/paris/en/town-framed-river'},
 priceEdict4:{title:'福特汉姆史料集：301 年最高限价敕令',url:'https://sourcebooks.web.fordham.edu/ancient/diocletian-control.asp'},
 britainCrisis4:{title:'英国遗产：四世纪不列颠的军队、粮运与危机',url:'https://www.english-heritage.org.uk/learn/story-of-england/romans/introduction/'},
 constantine4:{title:'罗马皇帝学术百科：君士坦丁一世',url:'https://roman-emperors.sites.luc.edu/conniei.htm'},
 constantius4:{title:'罗马皇帝学术百科：君士坦提乌斯二世',url:'https://roman-emperors.sites.luc.edu/constaii.htm'},
 julian4:{title:'罗马皇帝学术百科：尤利安',url:'https://roman-emperors.sites.luc.edu/julian.htm'},
 valens4:{title:'罗马皇帝学术百科：瓦伦斯与哥特战争',url:'https://roman-emperors.sites.luc.edu/valens.htm'},
 theodosius4:{title:'罗马皇帝学术百科：狄奥多西一世',url:'https://roman-emperors.sites.luc.edu/theo1.htm'},
 emperorIndex4:{title:'罗马皇帝学术百科：皇帝与争位者年表',url:'https://roman-emperors.sites.luc.edu/impindex.htm'},
 shapur4:{title:'伊朗百科全书：沙普尔二世（309—379）',url:'https://www.iranicaonline.org/articles/shapur-ii/'},
 armenia4:{title:'伊朗百科全书：亚美尼亚与伊朗，前伊斯兰时期',url:'https://www.iranicaonline.org/articles/armenia-ii/'},
 ammianus16:{title:'阿米阿努斯《历史》卷十六：高卢与斯特拉斯堡',url:'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Ammian/16*.html'},
 ammianus19:{title:'阿米阿努斯《历史》卷十九：阿米达围城',url:'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Ammian/19*.html'},
 ammianus24:{title:'阿米阿努斯《历史》卷二十四：363 年远征',url:'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Ammian/24*.html'},
 ammianus25:{title:'阿米阿努斯《历史》卷二十五：撤退与和议',url:'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Ammian/25*.html'},
 ammianus31:{title:'阿米阿努斯《历史》卷三十一：匈人、渡河与战役',url:'https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Ammian/31*.html'},
 religionLaw4:{title:'福特汉姆史料集：狄奥多西法典宗教条文',url:'https://sourcebooks.web.fordham.edu/source/codex-theod1.asp'},
 nicaea4:{title:'UNESCO：伊兹尼克古城（尼西亚）',url:'https://whc.unesco.org/en/tentativelists/5900/'},
 amida4:{title:'UNESCO：迪亚巴克尔城堡与底格里斯河景观',url:'https://whc.unesco.org/en/list/1488/'},
 edessa4:{title:'伊朗百科全书：埃德萨',url:'https://www.iranicaonline.org/articles/edessa/'},
 sasanianDynasty4:{title:'伊朗百科全书：萨珊王朝统治年代',url:'https://www.iranicaonline.org/articles/sasanian-dynasty/'},
 persecution4:{title:'优西比乌《教会史》卷八：迫害时期的记述',url:'https://www.newadvent.org/fathers/250108.htm'},
 milan4:{title:'福特汉姆史料集：313 年宗教宽容文书',url:'https://sourcebooks.web.fordham.edu/source/edict-milan.asp'},
};
