import {courseSources} from './course-sources';
const guides:Record<number,{title:string;orientation:string;people:string;reading:string;source:keyof typeof courseSources;places:[string,string][]}>={
 300:{title:'300 年：一个帝国，多处朝廷驻地',orientation:'先看西北的特里尔和意大利北部的米兰，再看海峡东侧的尼科米底亚与爱琴海北岸的塞萨洛尼基。罗马城仍存在，君士坦丁堡此时尚未成为新都。',people:'朝廷、军队与当地城市居民分别理解。“罗马”既是政治身份，也涉及各地不同的社会传统；驻地位置不表示族群边界。',reading:'第 98 讲「四帝共治」· PDF 792—798 页',source:'trierLate',places:[['trier','特里尔：高卢与莱茵方向'],['milan','米兰：意大利北部'],['nicomedia','尼科米底亚：今伊兹米特'],['thessaloniki','塞萨洛尼基：爱琴海北岸']]},
 400:{title:'400 年：把两部朝廷与区域中心一起看',orientation:'西部朝廷仍在米兰，402 年才迁往拉文纳；东部中心在君士坦丁堡。迦太基、亚历山大里亚位于地中海南岸，安条克位于东岸。不列颠的罗马行政统治尚未结束。',people:'希波的主教、北非城市居民、帝国官员和军队属于不同社会群体。宗教、语言与帝国归属在地图上分别说明。',reading:'第 99 讲「君士坦丁（上）」与第 113 讲「狄奥多西」· PDF 799—805、955—962 页',source:'byzantine',places:[['milan','米兰：西部朝廷'],['byzantium','君士坦丁堡：东部朝廷'],['carthage','迦太基：北非港口'],['hippo','希波：奥古斯丁'],['alexandria','亚历山大里亚：埃及'],['antioch','安条克：叙利亚'],['london','伦底尼乌姆：不列颠']]},
 500:{title:'500 年：西部诸王国与延续的东罗马',orientation:'沿地图从北向南比较：图尔奈的法兰克、里昂的勃艮第、图卢兹的西哥特、拉文纳的东哥特，再跨海到迦太基的汪达尔。君士坦丁堡仍是东罗马的都城。',people:'新王国的统治集团与地方罗马社会并存。例如汪达尔统治者仍依靠罗马化的北非精英维持地方制度；阿里乌派是宗教派别，不是人种。',reading:'第 133 讲「蛮族王国」与第 138 讲「墨洛温王朝」· PDF 1123—1129、1159—1168 页',source:'africaVandal',places:[['tournai','法兰克 → 图尔奈'],['lyon','勃艮第 → 里昂'],['toulouse','西哥特 → 图卢兹'],['ravenna','东哥特 → 拉文纳'],['carthage','汪达尔 → 迦太基'],['byzantium','东罗马 → 君士坦丁堡']]},
};
export function LateAntiquityGuide({year,onPlace,onYear}:{year:number;onPlace:(id:string)=>void;onYear:(year:number)=>void}){
 const guide=guides[year];if(!guide)return null;
 return <section className="late-guide" aria-label="晚期罗马阅读导览"><h2>{guide.title}</h2><p>{guide.orientation}</p><div className="h-site-links">{guide.places.map(([id,name])=><button key={id} onClick={()=>onPlace(id)}>{name}<span>定位并阅读 →</span></button>)}</div><h3>当时的居民</h3><p>{guide.people}</p><p className="late-reading">顾衡课程关联：{guide.reading}</p><a href={courseSources[guide.source].url} target="_blank" rel="noreferrer">核对资料：{courseSources[guide.source].title} ↗</a><p>比较三个时点</p><div className="late-year-links">{[300,400,500].map(y=><button key={y} aria-pressed={year===y} onClick={()=>onYear(y)}>{y} 年</button>)}</div><small>地点详情按适用年代显示；地图色块仍是参考疆界，未新增精确行政区或族群分布边界。</small></section>;
}
