export const roman300Sources={
 hadrian300:{title:'英国遗产：哈德良长城的建造、前推与延续',url:'https://www.english-heritage.org.uk/visit/places/hadrians-wall/hadrians-wall-history-and-stories/history/'},
 limes300:{title:'德国 Limesstraße：上日耳曼—雷提亚防线的变迁',url:'https://www.limesstrasse.de/deutsche-limes-strasse/ueber-uns/geschichte-des-limes'},
 jovian300:{title:'伊朗百科全书：363 年约维安和约与尼西比斯',url:'https://www.iranicaonline.org/articles/jovian/'},
 aquileia300:{title:'UNESCO：阿奎莱亚罗马城市与港口',url:'https://whc.unesco.org/en/list/825/'},
 gortyn300:{title:'普林斯顿古典遗址百科：戈尔廷',url:'https://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.04.0006%3Aentry%3Dgortyn'},
 paphos300:{title:'UNESCO：帕福斯的古代城市遗址',url:'https://whc.unesco.org/en/list/79/'},
 jerusalem300:{title:'以色列文物局：罗马埃利亚·卡皮托利纳的城市布局',url:'https://publications.iaa.org.il/cornerstone/vol10/iss1/13/'},
 narseh300:{title:'伊朗百科全书：萨珊国王纳尔塞',url:'https://www.iranicaonline.org/articles/narseh-sasanian-king/'},
 inscriptions300:{title:'大都会博物馆：罗马铭文与多语言社会',url:'https://www.metmuseum.org/essays/roman-inscriptions'},
 danube300:{title:'UNESCO：多瑙河罗马边防（西段）',url:'https://whc.unesco.org/en/list/1608/'},
 dacia300:{title:'UNESCO：达契亚边防的使用年代',url:'https://whc.unesco.org/en/list/1718/'},
 housesteads300:{title:'英国遗产：豪斯斯特兹的驻军与居民',url:'https://www.english-heritage.org.uk/visit/places/housesteads-roman-fort-hadrians-wall/history/'},
 merida300:{title:'UNESCO：梅里达与卢西塔尼亚',url:'https://whc.unesco.org/en/list/664/'},
 timgad300:{title:'UNESCO：提姆加德罗马殖民城市',url:'https://whc.unesco.org/en/list/194/'},
 volubilis300:{title:'ICOMOS：沃鲁比利斯与罗马撤离南廷吉塔纳',url:'https://whc.unesco.org/archive/advisory_body_evaluation/836bis.pdf'},
 cyrene300:{title:'UNESCO：昔兰尼遗址与罗马时期',url:'https://whc.unesco.org/en/list/190/'},
 ephesus300:{title:'UNESCO：以弗所与亚细亚行省',url:'https://whc.unesco.org/en/list/1018/'},
 bosra300:{title:'UNESCO：布斯拉与阿拉伯行省',url:'https://whc.unesco.org/en/list/22/'},
 sirmium300:{title:'Livius：西尔米乌姆的帝国驻地',url:'https://www.livius.org/articles/place/sirmium-sremska-mitrovica/'},
 serdica300:{title:'Livius：塞尔迪卡与内陆达契亚',url:'https://www.livius.org/articles/place/serdica-sofia/'},
 cappadocia300:{title:'Livius：卡帕多西亚的罗马时期',url:'https://www.livius.org/articles/place/cappadocia/cappadocia-3/'},
 franks300:{title:'Livius：三世纪法兰克群体与莱茵边防',url:'https://www.livius.org/articles/people/franks/'},
 alamanni300:{title:'Livius：阿勒曼尼群体',url:'https://www.livius.org/articles/people/alamanni/'},
 goths300:{title:'牛津古典辞典：哥特诸集团',url:'https://academic.oup.com/edited-volume/61673/chapter-abstract/548939812'},
 sarmatians300:{title:'Livius：萨尔马提亚诸集团',url:'https://www.livius.org/articles/people/sarmatians/'},
 bosporus300:{title:'加拿大乌克兰研究所：博斯普鲁斯王国',url:'https://www.encyclopediaofukraine.com/display.asp?linkpath=pages%5CB%5CO%5CBosporanKingdom.htm'},
 armenia300:{title:'伊朗百科全书：亚美尼亚与罗马、伊朗的关系',url:'https://www.iranicaonline.org/articles/armenia-ii/'},
 albania300:{title:'伊朗百科全书：高加索阿尔巴尼亚',url:'https://www.iranicaonline.org/articles/albania-iranian-aran-arm/'},
 mtskheta300:{title:'UNESCO：姆茨赫塔历史中心',url:'https://whc.unesco.org/en/list/708/'},
 vagharshapat300:{title:'UNESCO：瓦加尔沙帕特与埃奇米阿津',url:'https://whc.unesco.org/en/list/1011/'},
 picts300:{title:'苏格兰历史环境局：皮克特人与北部地域',url:'https://www.historicenvironment.scot/visit/all/picardy-symbol-stone/history-and-stories/'},
 ireland300:{title:'爱尔兰考古研究项目：铁器时代与罗马世界的往来',url:'https://discoveryprogramme.ie/projects/past-projects/late-iron-age-roman-ireland-project/'},
 north300:{title:'丹麦考古研究：罗马铁器时代的地方中心',url:'https://tidsskrift.dk/kuml/article/viewFile/102643/151704'},
 coptic300:{title:'牛津《罗马埃及手册》：科普特语',url:'https://academic.oup.com/edited-volume/28112/chapter-abstract/212258986'},
 aramaic300:{title:'伊朗百科全书：阿拉米语的地域与书写传统',url:'https://www.iranicaonline.org/articles/aramaic/i-general/'},
 dioceses300:{title:'瑞士历史辞典：维埃纳管区与约 314 年的行政名录',url:'https://hls-dhs-dss.ch/fr/articles/008424/2015-04-30/'},
 gallic300:{title:'Livius：高卢分立帝国的兴亡',url:'https://www.livius.org/articles/concept/gallic-empire/'},
 palmyra300:{title:'UNESCO：帕尔米拉遗址',url:'https://whc.unesco.org/en/list/23/'},
 salona300:{title:'克罗地亚百科全书：萨洛纳',url:'https://www.enciklopedija.hr/clanak/salona'},
 egypt300:{title:'大都会博物馆：罗马时期的埃及社会与文化',url:'https://www.metmuseum.org/essays/roman-egypt'},
 rhine300:{title:'UNESCO：下日耳曼罗马边防',url:'https://whc.unesco.org/en/list/1631/'},
 syene300:{title:'Livius：古代晚期努比亚与埃及南部边防',url:'https://www.livius.org/articles/place/nubia/late-ancient-nubia/'},
};
